"""Bootstrap service to populate catalog with 87 initial tools."""
from typing import List, Optional

from src.models.tool_descriptor import (
    AuthenticationMethod,
    IntegrationType,
    ToolCategory,
    ToolDescriptor,
)


class ToolCatalogBootstrap:
    """Bootstrap 87 MCP tools into catalog."""

    def __init__(self, settings=None):
        """Inicializa bootstrap com settings opcionais para endpoints configuráveis."""
        self._settings = settings

    @property
    def settings(self):
        """Lazy load settings para evitar import circular."""
        if self._settings is None:
            from src.config.settings import get_settings
            self._settings = get_settings()
        return self._settings

    def _get_endpoint(self, env_var: str, default: str) -> str:
        """Obtém endpoint de settings ou retorna default."""
        return getattr(self.settings, env_var, None) or default

    def get_initial_tools(self) -> List[ToolDescriptor]:
        """Get initial set of 87 tools across 6 categories."""
        tools = []

        # ANALYSIS TOOLS (15 tools)
        tools.extend(self._get_analysis_tools())

        # GENERATION TOOLS (20 tools)
        tools.extend(self._get_generation_tools())

        # TRANSFORMATION TOOLS (18 tools)
        tools.extend(self._get_transformation_tools())

        # VALIDATION TOOLS (12 tools)
        tools.extend(self._get_validation_tools())

        # AUTOMATION TOOLS (12 tools)
        tools.extend(self._get_automation_tools())

        # INTEGRATION TOOLS (10 tools)
        tools.extend(self._get_integration_tools())

        # Ensure all tools have active=True in metadata
        for tool in tools:
            if "active" not in tool.metadata:
                tool.metadata["active"] = True

        return tools

    def _get_analysis_tools(self) -> List[ToolDescriptor]:
        """Get ANALYSIS category tools."""
        return [
            ToolDescriptor(
                tool_id="sonarqube-001",
                tool_name="SonarQube",
                category=ToolCategory.ANALYSIS,
                capabilities=["code_quality", "code_smells", "technical_debt"],
                version="10.3.0",
                reputation_score=0.85,
                average_execution_time_ms=30000,
                cost_score=0.6,
                required_parameters={"project_key": "string", "sonar_url": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("SONARQUBE_URL", "http://sonarqube:9000/api"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://sonarqube.org",
                    "license": "LGPL-3.0",
                    "credential_env": "SONARQUBE_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="trivy-001",
                tool_name="Trivy",
                category=ToolCategory.ANALYSIS,
                capabilities=["vulnerability_scan", "container_scan", "iac_scan"],
                version="0.48.0",
                reputation_score=0.9,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"target": "string", "scan_type": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://trivy.dev",
                    "license": "Apache-2.0",
                    "cli_command": "trivy",
                    "docker_image": "aquasec/trivy:0.48.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="snyk-001",
                tool_name="Snyk",
                category=ToolCategory.ANALYSIS,
                capabilities=["dependency_scan", "security_scan", "license_check"],
                version="1.1200.0",
                reputation_score=0.88,
                average_execution_time_ms=20000,
                cost_score=0.7,
                required_parameters={"project_path": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://snyk.io",
                    "license": "Proprietary",
                    "cli_command": "snyk test",
                    "credential_env": "SNYK_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="semgrep-001",
                tool_name="Semgrep",
                category=ToolCategory.ANALYSIS,
                capabilities=["pattern_matching", "sast", "custom_rules"],
                version="1.50.0",
                reputation_score=0.82,
                average_execution_time_ms=25000,
                cost_score=0.2,
                required_parameters={"target": "string", "config": "string"},
                output_format="sarif",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://semgrep.dev",
                    "license": "LGPL-2.1",
                    "cli_command": "semgrep scan",
                    "docker_image": "returntocorp/semgrep:1.50.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="eslint-001",
                tool_name="ESLint",
                category=ToolCategory.ANALYSIS,
                capabilities=["javascript_linting", "typescript_linting", "code_style"],
                version="8.55.0",
                reputation_score=0.9,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"project_path": "string", "config": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://eslint.org",
                    "license": "MIT",
                    "cli_command": "eslint",
                },
            ),
            ToolDescriptor(
                tool_id="pylint-001",
                tool_name="Pylint",
                category=ToolCategory.ANALYSIS,
                capabilities=["python_linting", "code_quality", "pep8"],
                version="3.0.3",
                reputation_score=0.87,
                average_execution_time_ms=12000,
                cost_score=0.1,
                required_parameters={"file_path": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://pylint.org",
                    "license": "GPL-2.0",
                    "cli_command": "pylint",
                },
            ),
            ToolDescriptor(
                tool_id="bandit-001",
                tool_name="Bandit",
                category=ToolCategory.ANALYSIS,
                capabilities=["python_security", "sast", "vulnerability_detection"],
                version="1.7.5",
                reputation_score=0.83,
                average_execution_time_ms=8000,
                cost_score=0.1,
                required_parameters={"target": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://bandit.readthedocs.io",
                    "license": "Apache-2.0",
                    "cli_command": "bandit",
                },
            ),
            ToolDescriptor(
                tool_id="codeql-001",
                tool_name="CodeQL",
                category=ToolCategory.ANALYSIS,
                capabilities=["semantic_analysis", "sast", "vulnerability_detection"],
                version="2.15.3",
                reputation_score=0.91,
                average_execution_time_ms=45000,
                cost_score=0.3,
                required_parameters={"database": "string", "query": "string"},
                output_format="sarif",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://codeql.github.com",
                    "license": "MIT",
                    "cli_command": "codeql database analyze",
                },
            ),
            ToolDescriptor(
                tool_id="owasp-dep-check-001",
                tool_name="OWASP Dependency-Check",
                category=ToolCategory.ANALYSIS,
                capabilities=["dependency_scan", "cve_detection", "sca"],
                version="9.0.7",
                reputation_score=0.84,
                average_execution_time_ms=35000,
                cost_score=0.1,
                required_parameters={"project": "string", "scan": "string"},
                output_format="xml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://owasp.org/www-project-dependency-check",
                    "license": "Apache-2.0",
                    "cli_command": "dependency-check",
                },
            ),
            ToolDescriptor(
                tool_id="checkmarx-001",
                tool_name="Checkmarx",
                category=ToolCategory.ANALYSIS,
                capabilities=["sast", "security_scan", "compliance"],
                version="9.3.0",
                reputation_score=0.88,
                average_execution_time_ms=60000,
                cost_score=0.9,
                required_parameters={"project_id": "string", "scan_type": "string"},
                output_format="xml",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("CHECKMARX_URL", "https://checkmarx.example.com/api"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://checkmarx.com",
                    "license": "Proprietary",
                    "credential_env": "CHECKMARX_API_KEY",
                },
            ),
            ToolDescriptor(
                tool_id="veracode-001",
                tool_name="Veracode",
                category=ToolCategory.ANALYSIS,
                capabilities=["sast", "dast", "compliance"],
                version="3.0",
                reputation_score=0.87,
                average_execution_time_ms=90000,
                cost_score=0.95,
                required_parameters={"app_id": "string"},
                output_format="xml",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("VERACODE_URL", "https://analysiscenter.veracode.com/api"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://veracode.com",
                    "license": "Proprietary",
                    "credential_env": "VERACODE_API_ID,VERACODE_API_KEY",
                },
            ),
            ToolDescriptor(
                tool_id="fortify-001",
                tool_name="Fortify",
                category=ToolCategory.ANALYSIS,
                capabilities=["sast", "security_scan"],
                version="23.1",
                reputation_score=0.86,
                average_execution_time_ms=75000,
                cost_score=0.9,
                required_parameters={"project": "string"},
                output_format="fpr",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("FORTIFY_URL", "https://fortify.example.com/api"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://www.microfocus.com/fortify",
                    "license": "Proprietary",
                    "credential_env": "FORTIFY_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="pmd-001",
                tool_name="PMD",
                category=ToolCategory.ANALYSIS,
                capabilities=["static_analysis", "java", "code_quality"],
                version="7.0.0",
                reputation_score=0.82,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"source_dir": "string", "ruleset": "string"},
                output_format="xml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://pmd.github.io", "license": "BSD-2-Clause", "cli_command": "pmd check"},
            ),
            ToolDescriptor(
                tool_id="spotbugs-001",
                tool_name="SpotBugs",
                category=ToolCategory.ANALYSIS,
                capabilities=["bug_detection", "java"],
                version="4.8.2",
                reputation_score=0.81,
                average_execution_time_ms=20000,
                cost_score=0.1,
                required_parameters={"class_path": "string"},
                output_format="xml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://spotbugs.github.io", "license": "LGPL-2.1", "cli_command": "spotbugs"},
            ),
            ToolDescriptor(
                tool_id="clang-analyzer-001",
                tool_name="Clang Static Analyzer",
                category=ToolCategory.ANALYSIS,
                capabilities=["static_analysis", "c", "cpp"],
                version="17.0.0",
                reputation_score=0.85,
                average_execution_time_ms=25000,
                cost_score=0.1,
                required_parameters={"source": "string", "compile_commands": "string"},
                output_format="plist",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://clang.llvm.org", "license": "Apache-2.0", "cli_command": "clang --analyze"},
            ),
            ToolDescriptor(
                tool_id="hadolint-001",
                tool_name="Hadolint",
                category=ToolCategory.ANALYSIS,
                capabilities=["dockerfile_lint", "best_practices"],
                version="2.12.0",
                reputation_score=0.78,
                average_execution_time_ms=2000,
                cost_score=0.1,
                required_parameters={"dockerfile": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://github.com/hadolint/hadolint",
                    "license": "GPL-3.0",
                    "cli_command": "hadolint",
                    "docker_image": "hadolint/hadolint:2.12.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="shellcheck-001",
                tool_name="Shellcheck",
                category=ToolCategory.ANALYSIS,
                capabilities=["shell_script_analysis", "bash"],
                version="0.9.0",
                reputation_score=0.83,
                average_execution_time_ms=3000,
                cost_score=0.1,
                required_parameters={"script": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://www.shellcheck.net",
                    "license": "GPL-3.0",
                    "cli_command": "shellcheck",
                    "docker_image": "koalaman/shellcheck:v0.9.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="gitleaks-001",
                tool_name="Gitleaks",
                category=ToolCategory.ANALYSIS,
                capabilities=["secret_detection", "security"],
                version="8.18.0",
                reputation_score=0.84,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"repo_path": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://gitleaks.io",
                    "license": "MIT",
                    "cli_command": "gitleaks detect",
                    "docker_image": "zricethezav/gitleaks:v8.18.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="trufflehog-001",
                tool_name="TruffleHog",
                category=ToolCategory.ANALYSIS,
                capabilities=["secret_scanning", "git_history"],
                version="3.63.2",
                reputation_score=0.82,
                average_execution_time_ms=8000,
                cost_score=0.1,
                required_parameters={"target": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://trufflesecurity.com",
                    "license": "AGPL-3.0",
                    "cli_command": "trufflehog",
                },
            ),
        ]

    def _get_generation_tools(self) -> List[ToolDescriptor]:
        """Get GENERATION category tools."""
        return [
            ToolDescriptor(
                tool_id="github-copilot-001",
                tool_name="GitHub Copilot",
                category=ToolCategory.GENERATION,
                capabilities=["code_completion", "code_generation", "ai_assisted"],
                version="1.140.0",
                reputation_score=0.85,
                average_execution_time_ms=2000,
                cost_score=0.8,
                required_parameters={"prompt": "string", "language": "string"},
                output_format="text",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("GITHUB_COPILOT_URL", "https://api.github.com/copilot"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://github.com/features/copilot",
                    "license": "Proprietary",
                    "credential_env": "GITHUB_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="openapi-generator-001",
                tool_name="OpenAPI Generator",
                category=ToolCategory.GENERATION,
                capabilities=["api_client_generation", "server_stub_generation", "openapi"],
                version="7.2.0",
                reputation_score=0.88,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"spec_file": "string", "generator": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://openapi-generator.tech",
                    "license": "Apache-2.0",
                    "cli_command": "openapi-generator-cli generate",
                },
            ),
            ToolDescriptor(
                tool_id="terraform-cdk-001",
                tool_name="Terraform CDK",
                category=ToolCategory.GENERATION,
                capabilities=["iac_generation", "terraform", "cdk"],
                version="0.19.0",
                reputation_score=0.8,
                average_execution_time_ms=20000,
                cost_score=0.1,
                required_parameters={"language": "string", "provider": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://terraform.io/cdktf",
                    "license": "MPL-2.0",
                    "cli_command": "cdktf",
                },
            ),
            ToolDescriptor(
                tool_id="cookiecutter-001",
                tool_name="Cookiecutter",
                category=ToolCategory.GENERATION,
                capabilities=["project_scaffolding", "templates", "boilerplate"],
                version="2.5.0",
                reputation_score=0.82,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"template": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://cookiecutter.io",
                    "license": "BSD-3-Clause",
                    "cli_command": "cookiecutter",
                },
            ),
            ToolDescriptor(
                tool_id="tabnine-001",
                tool_name="Tabnine",
                category=ToolCategory.GENERATION,
                capabilities=["code_completion", "ai_assisted"],
                version="5.9.0",
                reputation_score=0.88,
                average_execution_time_ms=500,
                cost_score=0.6,
                required_parameters={"language": "string"},
                output_format="text",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://tabnine.com", "license": "Proprietary"},
            ),
            ToolDescriptor(
                tool_id="swagger-codegen-001",
                tool_name="Swagger Codegen",
                category=ToolCategory.GENERATION,
                capabilities=["api_client_generation", "openapi"],
                version="3.0.50",
                reputation_score=0.85,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"spec_file": "string", "language": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://swagger.io/tools/swagger-codegen",
                    "license": "Apache-2.0",
                    "cli_command": "swagger-codegen generate",
                },
            ),
            ToolDescriptor(
                tool_id="yeoman-001",
                tool_name="Yeoman",
                category=ToolCategory.GENERATION,
                capabilities=["scaffolding", "project_generation", "templates"],
                version="4.3.1",
                reputation_score=0.79,
                average_execution_time_ms=8000,
                cost_score=0.1,
                required_parameters={"generator": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://yeoman.io",
                    "license": "BSD-2-Clause",
                    "cli_command": "yo",
                },
            ),
            ToolDescriptor(
                tool_id="jhipster-001",
                tool_name="JHipster",
                category=ToolCategory.GENERATION,
                capabilities=["full_stack_generation", "spring_boot", "angular_react"],
                version="8.1.0",
                reputation_score=0.86,
                average_execution_time_ms=60000,
                cost_score=0.1,
                required_parameters={"project_type": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://jhipster.tech",
                    "license": "Apache-2.0",
                    "cli_command": "jhipster",
                },
            ),
            ToolDescriptor(
                tool_id="spring-initializr-001",
                tool_name="Spring Initializr",
                category=ToolCategory.GENERATION,
                capabilities=["spring_boot_generator"],
                version="0.21.0",
                reputation_score=0.91,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"dependencies": "string", "type": "string"},
                output_format="zip",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("SPRING_INITIALIZR_URL", "https://start.spring.io"),
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://start.spring.io",
                    "license": "Apache-2.0",
                },
            ),
            ToolDescriptor(
                tool_id="create-react-app-001",
                tool_name="Create React App",
                category=ToolCategory.GENERATION,
                capabilities=["react_scaffolding", "spa_generation", "webpack_config"],
                version="5.0.1",
                reputation_score=0.89,
                average_execution_time_ms=25000,
                cost_score=0.1,
                required_parameters={"project_name": "string", "template": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://create-react-app.dev",
                    "license": "MIT",
                    "cli_command": "npx create-react-app",
                },
            ),
            ToolDescriptor(
                tool_id="vue-cli-001",
                tool_name="Vue CLI",
                category=ToolCategory.GENERATION,
                capabilities=["vue_scaffolding", "spa_generation", "project_setup"],
                version="5.0.8",
                reputation_score=0.86,
                average_execution_time_ms=20000,
                cost_score=0.1,
                required_parameters={"preset": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://cli.vuejs.org",
                    "license": "MIT",
                    "cli_command": "vue create",
                },
            ),
            ToolDescriptor(
                tool_id="angular-cli-001",
                tool_name="Angular CLI",
                category=ToolCategory.GENERATION,
                capabilities=["angular_scaffolding", "spa_generation", "project_setup"],
                version="17.0.0",
                reputation_score=0.88,
                average_execution_time_ms=22000,
                cost_score=0.1,
                required_parameters={"name": "string", "style": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://angular.io/cli",
                    "license": "MIT",
                    "cli_command": "ng new",
                },
            ),
            ToolDescriptor(
                tool_id="pulumi-001",
                tool_name="Pulumi",
                category=ToolCategory.GENERATION,
                capabilities=["iac_generation", "cloud_infrastructure", "multi_cloud"],
                version="3.96.0",
                reputation_score=0.84,
                average_execution_time_ms=15000,
                cost_score=0.2,
                required_parameters={"stack": "string", "language": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://pulumi.com",
                    "license": "Apache-2.0",
                    "cli_command": "pulumi",
                    "credential_env": "PULUMI_ACCESS_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="aws-cdk-001",
                tool_name="AWS CDK",
                category=ToolCategory.GENERATION,
                capabilities=["aws_iac", "cloudformation", "infrastructure_code"],
                version="2.115.0",
                reputation_score=0.86,
                average_execution_time_ms=18000,
                cost_score=0.1,
                required_parameters={"language": "string", "stack": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://aws.amazon.com/cdk",
                    "license": "Apache-2.0",
                    "cli_command": "cdk",
                },
            ),
            ToolDescriptor(
                tool_id="serverless-001",
                tool_name="Serverless Framework",
                category=ToolCategory.GENERATION,
                capabilities=["serverless_generation", "lambda", "multi_cloud"],
                version="3.38.0",
                reputation_score=0.85,
                average_execution_time_ms=12000,
                cost_score=0.1,
                required_parameters={"template": "string", "provider": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://serverless.com",
                    "license": "MIT",
                    "cli_command": "serverless",
                },
            ),
            ToolDescriptor(
                tool_id="helm-generator-001",
                tool_name="Helm Chart Generator",
                category=ToolCategory.GENERATION,
                capabilities=["helm_charts", "kubernetes", "chart_generation"],
                version="3.13.0",
                reputation_score=0.82,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"chart_name": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://helm.sh",
                    "license": "Apache-2.0",
                    "cli_command": "helm create",
                },
            ),
            ToolDescriptor(
                tool_id="dockerfile-gen-001",
                tool_name="Dockerfile Generator",
                category=ToolCategory.GENERATION,
                capabilities=["dockerfile_generation", "container", "optimization"],
                version="1.0.0",
                reputation_score=0.76,
                average_execution_time_ms=2000,
                cost_score=0.1,
                required_parameters={"base_image": "string", "language": "string"},
                output_format="text",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://github.com/dockerfile-generator", "license": "MIT"},
            ),
            ToolDescriptor(
                tool_id="pytest-gen-001",
                tool_name="Pytest Test Generator",
                category=ToolCategory.GENERATION,
                capabilities=["test_generation", "python", "unit_tests"],
                version="0.2.0",
                reputation_score=0.74,
                average_execution_time_ms=3000,
                cost_score=0.1,
                required_parameters={"source_file": "string"},
                output_format="text",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://pytest.org", "license": "MIT"},
            ),
            ToolDescriptor(
                tool_id="jest-gen-001",
                tool_name="Jest Test Generator",
                category=ToolCategory.GENERATION,
                capabilities=["test_generation", "javascript", "unit_tests"],
                version="29.7.0",
                reputation_score=0.75,
                average_execution_time_ms=3000,
                cost_score=0.1,
                required_parameters={"source_file": "string"},
                output_format="text",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://jestjs.io", "license": "MIT"},
            ),
            ToolDescriptor(
                tool_id="openai-codex-001",
                tool_name="OpenAI Codex",
                category=ToolCategory.GENERATION,
                capabilities=["ai_code_generation", "llm", "multi_language"],
                version="1.0",
                reputation_score=0.87,
                average_execution_time_ms=3000,
                cost_score=0.8,
                required_parameters={"prompt": "string", "model": "string"},
                output_format="text",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("OPENAI_CODEX_URL", "https://api.openai.com/v1"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://openai.com",
                    "license": "Proprietary",
                    "credential_env": "OPENAI_API_KEY",
                },
            ),
        ]

    def _get_transformation_tools(self) -> List[ToolDescriptor]:
        """Get TRANSFORMATION category tools."""
        return [
            ToolDescriptor(
                tool_id="prettier-001",
                tool_name="Prettier",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["code_formatting", "javascript", "typescript", "css"],
                version="3.1.1",
                reputation_score=0.92,
                average_execution_time_ms=3000,
                cost_score=0.1,
                required_parameters={"file_path": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://prettier.io",
                    "license": "MIT",
                    "cli_command": "prettier --write",
                },
            ),
            ToolDescriptor(
                tool_id="black-001",
                tool_name="Black",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["python_formatting", "pep8"],
                version="23.12.0",
                reputation_score=0.9,
                average_execution_time_ms=2000,
                cost_score=0.1,
                required_parameters={"file_path": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://black.readthedocs.io",
                    "license": "MIT",
                    "cli_command": "black",
                },
            ),
            ToolDescriptor(
                tool_id="terraform-fmt-001",
                tool_name="Terraform fmt",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["terraform_formatting", "hcl"],
                version="1.6.6",
                reputation_score=0.85,
                average_execution_time_ms=1000,
                cost_score=0.1,
                required_parameters={"file_path": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://terraform.io",
                    "license": "MPL-2.0",
                    "cli_command": "terraform fmt",
                },
            ),
            ToolDescriptor(
                tool_id="babel-001",
                tool_name="Babel",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["transpiling", "javascript"],
                version="7.23.0",
                reputation_score=0.91,
                average_execution_time_ms=8000,
                cost_score=0.1,
                required_parameters={"source": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://babeljs.io", "license": "MIT", "cli_command": "babel"},
            ),
            ToolDescriptor(
                tool_id="tsc-001",
                tool_name="TypeScript Compiler",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["transpiling", "typescript"],
                version="5.3.0",
                reputation_score=0.93,
                average_execution_time_ms=12000,
                cost_score=0.1,
                required_parameters={"tsconfig": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://typescriptlang.org", "license": "Apache-2.0", "cli_command": "tsc"},
            ),
            ToolDescriptor(
                tool_id="webpack-001",
                tool_name="Webpack",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["bundling", "javascript"],
                version="5.89.0",
                reputation_score=0.89,
                average_execution_time_ms=20000,
                cost_score=0.1,
                required_parameters={"config": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://webpack.js.org", "license": "MIT", "cli_command": "webpack"},
            ),
            ToolDescriptor(
                tool_id="rollup-001",
                tool_name="Rollup",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["bundling", "tree_shaking"],
                version="4.9.0",
                reputation_score=0.86,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"config": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://rollupjs.org", "license": "MIT", "cli_command": "rollup"},
            ),
            ToolDescriptor(
                tool_id="parcel-001",
                tool_name="Parcel",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["bundling", "zero_config"],
                version="2.11.0",
                reputation_score=0.84,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"entry": "string"},
                output_format="files",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://parceljs.org", "license": "MIT", "cli_command": "parcel build"},
            ),
            ToolDescriptor(
                tool_id="ansible-lint-001",
                tool_name="Ansible Lint",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["ansible_validation", "best_practices"],
                version="24.2.0",
                reputation_score=0.82,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"playbook": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://ansible-lint.readthedocs.io", "license": "MIT", "cli_command": "ansible-lint"},
            ),
            ToolDescriptor(
                tool_id="kustomize-001",
                tool_name="Kustomize",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["kubernetes_manifest_transformation"],
                version="5.3.0",
                reputation_score=0.85,
                average_execution_time_ms=3000,
                cost_score=0.1,
                required_parameters={"kustomization": "string"},
                output_format="yaml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://kustomize.io", "license": "Apache-2.0", "cli_command": "kustomize build"},
            ),
            ToolDescriptor(
                tool_id="openapi-transformer-001",
                tool_name="OpenAPI Transformer",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["openapi_transformation"],
                version="1.0.0",
                reputation_score=0.77,
                average_execution_time_ms=2000,
                cost_score=0.1,
                required_parameters={"spec": "string", "target_version": "string"},
                output_format="json",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://github.com/openapi-transformer", "license": "MIT"},
            ),
            ToolDescriptor(
                tool_id="graphql-stitching-001",
                tool_name="GraphQL Schema Stitching",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["graphql_schema_merge"],
                version="8.5.0",
                reputation_score=0.79,
                average_execution_time_ms=4000,
                cost_score=0.1,
                required_parameters={"schemas": "array"},
                output_format="graphql",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://graphql-tools.com", "license": "MIT"},
            ),
            ToolDescriptor(
                tool_id="flyway-001",
                tool_name="Flyway",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["database_migration", "sql"],
                version="10.4.0",
                reputation_score=0.88,
                average_execution_time_ms=10000,
                cost_score=0.3,
                required_parameters={"url": "string", "locations": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://flywaydb.org", "license": "Apache-2.0", "cli_command": "flyway migrate"},
            ),
            ToolDescriptor(
                tool_id="liquibase-001",
                tool_name="Liquibase",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["database_migration", "xml"],
                version="4.25.0",
                reputation_score=0.87,
                average_execution_time_ms=12000,
                cost_score=0.3,
                required_parameters={"changelog": "string", "url": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://liquibase.org", "license": "Apache-2.0", "cli_command": "liquibase update"},
            ),
            ToolDescriptor(
                tool_id="uglifyjs-001",
                tool_name="UglifyJS",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["minification", "javascript"],
                version="3.17.4",
                reputation_score=0.83,
                average_execution_time_ms=6000,
                cost_score=0.1,
                required_parameters={"source": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://github.com/mishoo/UglifyJS", "license": "BSD-2-Clause", "cli_command": "uglifyjs"},
            ),
            ToolDescriptor(
                tool_id="terser-001",
                tool_name="Terser",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["minification", "es6"],
                version="5.26.0",
                reputation_score=0.85,
                average_execution_time_ms=7000,
                cost_score=0.1,
                required_parameters={"source": "string"},
                output_format="text",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://terser.org", "license": "BSD-2-Clause", "cli_command": "terser"},
            ),
            ToolDescriptor(
                tool_id="docker-compose-converter-001",
                tool_name="Docker Compose Converter",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["compose_to_kubernetes", "swarm_conversion"],
                version="1.0.0",
                reputation_score=0.74,
                average_execution_time_ms=4000,
                cost_score=0.1,
                required_parameters={"compose_file": "string"},
                output_format="yaml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://github.com/docker/compose", "license": "Apache-2.0"},
            ),
            ToolDescriptor(
                tool_id="refactoring-tools-001",
                tool_name="Refactoring Tools",
                category=ToolCategory.TRANSFORMATION,
                capabilities=["code_refactoring", "automated_cleanup", "pattern_application"],
                version="1.0.0",
                reputation_score=0.77,
                average_execution_time_ms=20000,
                cost_score=0.1,
                required_parameters={"source": "string", "refactoring": "string"},
                output_format="text",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://refactoring.com", "license": "MIT"},
            ),
        ]

    def _get_validation_tools(self) -> List[ToolDescriptor]:
        """Get VALIDATION category tools."""
        return [
            ToolDescriptor(
                tool_id="pytest-001",
                tool_name="Pytest",
                category=ToolCategory.VALIDATION,
                capabilities=["python_testing", "unit_tests", "integration_tests"],
                version="7.4.3",
                reputation_score=0.95,
                average_execution_time_ms=30000,
                cost_score=0.1,
                required_parameters={"test_path": "string"},
                output_format="xml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://pytest.org",
                    "license": "MIT",
                    "cli_command": "pytest",
                },
            ),
            ToolDescriptor(
                tool_id="jest-001",
                tool_name="Jest",
                category=ToolCategory.VALIDATION,
                capabilities=["javascript_testing", "react_testing", "snapshot_testing"],
                version="29.7.0",
                reputation_score=0.92,
                average_execution_time_ms=25000,
                cost_score=0.1,
                required_parameters={"test_path": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://jestjs.io",
                    "license": "MIT",
                    "cli_command": "jest",
                },
            ),
            ToolDescriptor(
                tool_id="checkov-001",
                tool_name="Checkov",
                category=ToolCategory.VALIDATION,
                capabilities=["iac_validation", "policy_as_code", "terraform_validation"],
                version="3.1.20",
                reputation_score=0.86,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"file_path": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://checkov.io",
                    "license": "Apache-2.0",
                    "cli_command": "checkov",
                    "docker_image": "bridgecrew/checkov:3.1.20",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="junit-001",
                tool_name="JUnit",
                category=ToolCategory.VALIDATION,
                capabilities=["unit_testing", "java"],
                version="5.10.1",
                reputation_score=0.92,
                average_execution_time_ms=8000,
                cost_score=0.1,
                required_parameters={"test_path": "string"},
                output_format="xml",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://junit.org", "license": "EPL-2.0"},
            ),
            ToolDescriptor(
                tool_id="selenium-001",
                tool_name="Selenium",
                category=ToolCategory.VALIDATION,
                capabilities=["e2e_testing", "browser_automation"],
                version="4.16.0",
                reputation_score=0.89,
                average_execution_time_ms=30000,
                cost_score=0.1,
                required_parameters={"url": "string", "driver": "string"},
                output_format="logs",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://selenium.dev", "license": "Apache-2.0"},
            ),
            ToolDescriptor(
                tool_id="cypress-001",
                tool_name="Cypress",
                category=ToolCategory.VALIDATION,
                capabilities=["e2e_testing", "javascript"],
                version="13.6.0",
                reputation_score=0.91,
                average_execution_time_ms=25000,
                cost_score=0.1,
                required_parameters={"spec": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://cypress.io", "license": "MIT", "cli_command": "cypress run"},
            ),
            ToolDescriptor(
                tool_id="newman-001",
                tool_name="Postman Newman",
                category=ToolCategory.VALIDATION,
                capabilities=["api_testing"],
                version="6.0.0",
                reputation_score=0.86,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"collection": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://learning.postman.com/docs/running-collections/using-newman-cli",
                    "license": "Apache-2.0",
                    "cli_command": "newman run",
                },
            ),
            ToolDescriptor(
                tool_id="k6-001",
                tool_name="K6",
                category=ToolCategory.VALIDATION,
                capabilities=["load_testing", "performance"],
                version="0.48.0",
                reputation_score=0.87,
                average_execution_time_ms=60000,
                cost_score=0.1,
                required_parameters={"script": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://k6.io", "license": "AGPL-3.0", "cli_command": "k6 run"},
            ),
            ToolDescriptor(
                tool_id="locust-001",
                tool_name="Locust",
                category=ToolCategory.VALIDATION,
                capabilities=["load_testing", "python"],
                version="2.20.0",
                reputation_score=0.84,
                average_execution_time_ms=45000,
                cost_score=0.1,
                required_parameters={"locustfile": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://locust.io", "license": "MIT", "cli_command": "locust"},
            ),
            ToolDescriptor(
                tool_id="owasp-zap-001",
                tool_name="OWASP ZAP",
                category=ToolCategory.VALIDATION,
                capabilities=["dast", "security_scanning", "penetration_testing"],
                version="2.14.0",
                reputation_score=0.88,
                average_execution_time_ms=120000,
                cost_score=0.1,
                required_parameters={"target": "string"},
                output_format="xml",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://zaproxy.org",
                    "license": "Apache-2.0",
                    "cli_command": "zap-cli",
                    "docker_image": "owasp/zap2docker-stable:2.14.0",
                    "container_enabled": True,
                },
            ),
            ToolDescriptor(
                tool_id="burp-001",
                tool_name="Burp Suite",
                category=ToolCategory.VALIDATION,
                capabilities=["penetration_testing", "security"],
                version="2023.11",
                reputation_score=0.9,
                average_execution_time_ms=120000,
                cost_score=0.95,
                required_parameters={"target": "string"},
                output_format="xml",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("BURP_SUITE_URL", "http://burpsuite:8080"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://portswigger.net/burp",
                    "license": "Proprietary",
                    "credential_env": "BURP_SUITE_API_KEY",
                },
            ),
            ToolDescriptor(
                tool_id="conftest-001",
                tool_name="Conftest",
                category=ToolCategory.VALIDATION,
                capabilities=["policy_validation", "opa", "kubernetes_policies"],
                version="0.48.0",
                reputation_score=0.82,
                average_execution_time_ms=5000,
                cost_score=0.1,
                required_parameters={"policy": "string", "input": "string"},
                output_format="json",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://conftest.dev",
                    "license": "Apache-2.0",
                    "cli_command": "conftest test",
                },
            ),
        ]

    def _get_automation_tools(self) -> List[ToolDescriptor]:
        """Get AUTOMATION category tools."""
        return [
            ToolDescriptor(
                tool_id="github-actions-001",
                tool_name="GitHub Actions",
                category=ToolCategory.AUTOMATION,
                capabilities=["ci_cd", "workflow_automation", "github_integration"],
                version="1.0",
                reputation_score=0.9,
                average_execution_time_ms=60000,
                cost_score=0.5,
                required_parameters={"workflow_file": "string"},
                output_format="yaml",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("GITHUB_ACTIONS_URL", "https://api.github.com"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://github.com/features/actions",
                    "license": "MIT",
                    "credential_env": "GITHUB_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="argocd-001",
                tool_name="ArgoCD",
                category=ToolCategory.AUTOMATION,
                capabilities=["gitops", "kubernetes_deployment", "continuous_delivery"],
                version="2.9.3",
                reputation_score=0.88,
                average_execution_time_ms=45000,
                cost_score=0.1,
                required_parameters={"app_name": "string", "repo_url": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("ARGOCD_URL", "http://argocd-server:80/api"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://argo-cd.readthedocs.io",
                    "license": "Apache-2.0",
                    "credential_env": "ARGOCD_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="gitlab-ci-001",
                tool_name="GitLab CI",
                category=ToolCategory.AUTOMATION,
                capabilities=["ci_cd", "gitlab"],
                version="16.7.0",
                reputation_score=0.88,
                average_execution_time_ms=180000,
                cost_score=0.1,
                required_parameters={"pipeline": "string"},
                output_format="logs",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("GITLAB_CI_URL", "https://gitlab.com/api/v4"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://gitlab.com",
                    "license": "MIT",
                    "credential_env": "GITLAB_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="jenkins-001",
                tool_name="Jenkins",
                category=ToolCategory.AUTOMATION,
                capabilities=["ci_cd", "automation"],
                version="2.430.0",
                reputation_score=0.85,
                average_execution_time_ms=120000,
                cost_score=0.1,
                required_parameters={"job": "string"},
                output_format="logs",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("JENKINS_URL", "http://jenkins:8080"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://jenkins.io",
                    "license": "MIT",
                    "credential_env": "JENKINS_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="circleci-001",
                tool_name="CircleCI",
                category=ToolCategory.AUTOMATION,
                capabilities=["ci_cd"],
                version="2.1",
                reputation_score=0.87,
                average_execution_time_ms=150000,
                cost_score=0.5,
                required_parameters={"config": "string"},
                output_format="logs",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("CIRCLECI_URL", "https://circleci.com/api/v2"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://circleci.com",
                    "license": "Proprietary",
                    "credential_env": "CIRCLECI_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="travis-001",
                tool_name="Travis CI",
                category=ToolCategory.AUTOMATION,
                capabilities=["ci_cd"],
                version="1.0",
                reputation_score=0.82,
                average_execution_time_ms=140000,
                cost_score=0.4,
                required_parameters={"config": "string"},
                output_format="logs",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("TRAVIS_CI_URL", "https://api.travis-ci.com"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://travis-ci.com",
                    "license": "Proprietary",
                    "credential_env": "TRAVIS_TOKEN",
                },
            ),
            ToolDescriptor(
                tool_id="flux-001",
                tool_name="Flux",
                category=ToolCategory.AUTOMATION,
                capabilities=["gitops", "kubernetes"],
                version="2.2.0",
                reputation_score=0.86,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"source": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://fluxcd.io",
                    "license": "Apache-2.0",
                    "cli_command": "flux",
                },
            ),
            ToolDescriptor(
                tool_id="tekton-001",
                tool_name="Tekton",
                category=ToolCategory.AUTOMATION,
                capabilities=["kubernetes_native_ci_cd"],
                version="0.56.0",
                reputation_score=0.83,
                average_execution_time_ms=90000,
                cost_score=0.1,
                required_parameters={"pipeline": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://tekton.dev",
                    "license": "Apache-2.0",
                    "cli_command": "tkn",
                },
            ),
            ToolDescriptor(
                tool_id="ansible-001",
                tool_name="Ansible",
                category=ToolCategory.AUTOMATION,
                capabilities=["configuration_management", "orchestration", "provisioning"],
                version="2.16.0",
                reputation_score=0.9,
                average_execution_time_ms=45000,
                cost_score=0.1,
                required_parameters={"playbook": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://ansible.com",
                    "license": "GPL-3.0",
                    "cli_command": "ansible-playbook",
                },
            ),
            ToolDescriptor(
                tool_id="terraform-001",
                tool_name="Terraform",
                category=ToolCategory.AUTOMATION,
                capabilities=["iac_automation", "provisioning", "multi_cloud"],
                version="1.6.6",
                reputation_score=0.92,
                average_execution_time_ms=30000,
                cost_score=0.1,
                required_parameters={"config": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://terraform.io",
                    "license": "MPL-2.0",
                    "cli_command": "terraform apply",
                },
            ),
            ToolDescriptor(
                tool_id="k8s-operators-001",
                tool_name="Kubernetes Operators",
                category=ToolCategory.AUTOMATION,
                capabilities=["automation", "kubernetes"],
                version="1.0",
                reputation_score=0.84,
                average_execution_time_ms=30000,
                cost_score=0.1,
                required_parameters={"operator": "string"},
                output_format="logs",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://kubernetes.io/docs/concepts/extend-kubernetes/operator", "license": "Apache-2.0"},
            ),
            ToolDescriptor(
                tool_id="helm-001",
                tool_name="Helm",
                category=ToolCategory.AUTOMATION,
                capabilities=["kubernetes_package_manager", "templating"],
                version="3.13.0",
                reputation_score=0.91,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"chart": "string"},
                output_format="logs",
                integration_type=IntegrationType.CLI,
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://helm.sh",
                    "license": "Apache-2.0",
                    "cli_command": "helm",
                },
            ),
        ]

    def _get_integration_tools(self) -> List[ToolDescriptor]:
        """Get INTEGRATION category tools."""
        return [
            ToolDescriptor(
                tool_id="kafka-connect-001",
                tool_name="Kafka Connect",
                category=ToolCategory.INTEGRATION,
                capabilities=["data_integration", "streaming", "connectors"],
                version="3.6.0",
                reputation_score=0.85,
                average_execution_time_ms=10000,
                cost_score=0.1,
                required_parameters={"connector_config": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("KAFKA_CONNECT_URL", "http://kafka-connect:8083"),
                authentication_method=AuthenticationMethod.NONE,
                metadata={
                    "homepage": "https://kafka.apache.org/documentation/#connect",
                    "license": "Apache-2.0",
                },
            ),
            ToolDescriptor(
                tool_id="airflow-001",
                tool_name="Apache Airflow",
                category=ToolCategory.INTEGRATION,
                capabilities=["workflow_orchestration", "dag", "scheduling"],
                version="2.8.0",
                reputation_score=0.87,
                average_execution_time_ms=20000,
                cost_score=0.2,
                required_parameters={"dag_id": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("AIRFLOW_URL", "http://airflow-webserver:8080/api/v1"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://airflow.apache.org",
                    "license": "Apache-2.0",
                },
            ),
            ToolDescriptor(
                tool_id="apache-camel-001",
                tool_name="Apache Camel",
                category=ToolCategory.INTEGRATION,
                capabilities=["eip", "routing", "mediation"],
                version="4.2.0",
                reputation_score=0.86,
                average_execution_time_ms=15000,
                cost_score=0.1,
                required_parameters={"route": "string"},
                output_format="logs",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.NONE,
                metadata={"homepage": "https://camel.apache.org", "license": "Apache-2.0"},
            ),
            ToolDescriptor(
                tool_id="mulesoft-001",
                tool_name="MuleSoft",
                category=ToolCategory.INTEGRATION,
                capabilities=["api_integration", "esb", "dataweave"],
                version="4.5.0",
                reputation_score=0.82,
                average_execution_time_ms=20000,
                cost_score=0.9,
                required_parameters={"flow": "string"},
                output_format="logs",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("MULESOFT_URL", "https://anypoint.mulesoft.com/api"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://mulesoft.com",
                    "license": "Proprietary",
                    "credential_env": "MULESOFT_CLIENT_ID,MULESOFT_CLIENT_SECRET",
                },
            ),
            ToolDescriptor(
                tool_id="zapier-001",
                tool_name="Zapier",
                category=ToolCategory.INTEGRATION,
                capabilities=["workflow_automation", "app_integration", "no_code"],
                version="1.0",
                reputation_score=0.79,
                average_execution_time_ms=5000,
                cost_score=0.6,
                required_parameters={"zap": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url="https://api.zapier.com",
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://zapier.com",
                    "license": "Proprietary",
                },
            ),
            ToolDescriptor(
                tool_id="ifttt-001",
                tool_name="IFTTT",
                category=ToolCategory.INTEGRATION,
                capabilities=["automation", "iot_integration", "applets"],
                version="1.0",
                reputation_score=0.75,
                average_execution_time_ms=3000,
                cost_score=0.5,
                required_parameters={"applet": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url="https://platform.ifttt.com",
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://ifttt.com",
                    "license": "Proprietary",
                },
            ),
            ToolDescriptor(
                tool_id="aws-eventbridge-001",
                tool_name="AWS EventBridge",
                category=ToolCategory.INTEGRATION,
                capabilities=["event_bus", "serverless_integration", "event_routing"],
                version="1.0",
                reputation_score=0.88,
                average_execution_time_ms=2000,
                cost_score=0.3,
                required_parameters={"rule": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("AWS_EVENTBRIDGE_URL", "https://events.amazonaws.com"),
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={
                    "homepage": "https://aws.amazon.com/eventbridge",
                    "license": "Proprietary",
                    "credential_env": "AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY",
                },
            ),
            ToolDescriptor(
                tool_id="azure-logic-apps-001",
                tool_name="Azure Logic Apps",
                category=ToolCategory.INTEGRATION,
                capabilities=["workflow_automation", "enterprise_integration", "connectors"],
                version="1.0",
                reputation_score=0.84,
                average_execution_time_ms=10000,
                cost_score=0.6,
                required_parameters={"workflow": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("AZURE_LOGIC_APPS_URL", "https://management.azure.com"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://azure.microsoft.com/en-us/services/logic-apps",
                    "license": "Proprietary",
                    "credential_env": "AZURE_CLIENT_ID,AZURE_CLIENT_SECRET,AZURE_TENANT_ID",
                },
            ),
            ToolDescriptor(
                tool_id="google-workflows-001",
                tool_name="Google Cloud Workflows",
                category=ToolCategory.INTEGRATION,
                capabilities=["orchestration", "serverless_workflows", "gcp_integration"],
                version="1.0",
                reputation_score=0.83,
                average_execution_time_ms=8000,
                cost_score=0.4,
                required_parameters={"workflow": "string"},
                output_format="json",
                integration_type=IntegrationType.REST_API,
                endpoint_url=self._get_endpoint("GOOGLE_WORKFLOWS_URL", "https://workflowexecutions.googleapis.com"),
                authentication_method=AuthenticationMethod.OAUTH2,
                metadata={
                    "homepage": "https://cloud.google.com/workflows",
                    "license": "Proprietary",
                    "credential_env": "GOOGLE_CREDENTIALS_JSON",
                },
            ),
            ToolDescriptor(
                tool_id="prefect-001",
                tool_name="Prefect",
                category=ToolCategory.INTEGRATION,
                capabilities=["workflow_orchestration", "data_pipelines", "monitoring"],
                version="2.14.0",
                reputation_score=0.81,
                average_execution_time_ms=15000,
                cost_score=0.2,
                required_parameters={"flow": "string"},
                output_format="logs",
                integration_type=IntegrationType.LIBRARY,
                authentication_method=AuthenticationMethod.API_KEY,
                metadata={"homepage": "https://prefect.io", "license": "Apache-2.0"},
            ),
        ]
