# Kustomization para Agentes - Staging
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: neural-hive-staging

resources:
  - worker-agents.yaml
  - queen-agent.yaml
  - analyst-agents.yaml
  - scout-agents.yaml
  - guard-agents.yaml
  - optimizer-agents.yaml
