apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "data-migration.fullname" . }}
  labels:
    {{- include "data-migration.labels" . | nindent 4 }}
data:
  SERVICE_VERSION: "{{ .Chart.AppVersion }}"
  PYTHONUNBUFFERED: "1"
  PYTHONDONTWRITEBYTECODE: "1"
  {{- if .Values.observability.enabled }}
  OBSERVABILITY_ENABLED: "true"
  {{- end }}
  {{- if .Values.config.kafka.enabled }}
  KAFKA_ENABLED: "true"
  {{- end }}
