from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, field_validator

from src.models.optimization_event import Adjustment, OptimizationType, CausalAnalysis


class OptimizationHypothesis(BaseModel):
    """Hypothesis for optimization generated by Optimization Engine."""

    hypothesis_id: str = Field(..., description="Unique identifier (UUID)")
    hypothesis_text: str = Field(..., description="Textual description of hypothesis")
    target_component: str = Field(..., description="Target component")
    optimization_type: OptimizationType = Field(..., description="Type of optimization")
    proposed_adjustments: List[Adjustment] = Field(..., description="Proposed adjustments")
    expected_improvement: float = Field(..., ge=0.0, le=1.0, description="Expected improvement")
    confidence_score: float = Field(..., ge=0.0, le=1.0, description="Confidence in hypothesis")
    risk_score: float = Field(..., ge=0.0, le=1.0, description="Risk of the change")
    causal_evidence: Optional[CausalAnalysis] = Field(None, description="Causal evidence")
    baseline_metrics: Dict[str, float] = Field(..., description="Current metrics")
    target_metrics: Dict[str, float] = Field(..., description="Target metrics")
    priority: int = Field(..., ge=1, le=5, description="Priority (1-5)")
    requires_experiment: bool = Field(default=True, description="Requires validation")
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Creation timestamp")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")

    @field_validator("expected_improvement", "confidence_score", "risk_score")
    @classmethod
    def validate_percentage(cls, v: float) -> float:
        if not 0.0 <= v <= 1.0:
            raise ValueError("Value must be between 0.0 and 1.0")
        return v

    @field_validator("priority")
    @classmethod
    def validate_priority(cls, v: int) -> int:
        if not 1 <= v <= 5:
            raise ValueError("Priority must be between 1 and 5")
        return v

    def to_experiment_request(self) -> Dict[str, Any]:
        """Convert hypothesis to ExperimentRequest structure."""
        return {
            "hypothesis": self.hypothesis_text,
            "objective": f"Validate {self.optimization_type.value} for {self.target_component}",
            "experiment_type": "A_B_TEST",
            "target_component": self.target_component,
            "baseline_configuration": {k: str(v) for k, v in self.baseline_metrics.items()},
            "experimental_configuration": {
                adj.parameter_name: adj.new_value for adj in self.proposed_adjustments
            },
            "success_criteria": [
                {
                    "metric_name": metric,
                    "operator": "GTE" if self.target_metrics[metric] >= self.baseline_metrics.get(metric, 0) else "LTE",
                    "threshold": target_value,
                    "confidence_level": self.confidence_score,
                }
                for metric, target_value in self.target_metrics.items()
            ],
        }

    def validate_feasibility(self) -> bool:
        """Validate if hypothesis is feasible."""
        # Check if we have baseline metrics
        if not self.baseline_metrics:
            return False

        # Check if target metrics are realistic
        for metric, target_value in self.target_metrics.items():
            if metric in self.baseline_metrics:
                baseline_value = self.baseline_metrics[metric]
                # Check if improvement is too optimistic (>100%)
                if target_value > baseline_value * 2:
                    return False

        # Check if risk is acceptable
        if self.risk_score > 0.8:
            return False

        return True
