apiVersion: v1
kind: Service
metadata:
  name: documentation-generation
  labels:
    app: documentation-generation
    service: documentation-generation
spec:
  type: ClusterIP
  selector:
    app: documentation-generation
  ports:
  - name: http
    port: 8014
    targetPort: 8014
    protocol: TCP
