"""
Geração de código heurística para fallback.

Módulo interno para geração de código quando CodeComposer não está disponível.
"""

from datetime import datetime


def generate_code_heuristic(
    service_name: str,
    language: str,
    description: str,
    requirements: list
) -> str:
    """
    Gera código baseado em heurística (regras determinísticas).

    Args:
        service_name: Nome do serviço
        language: Linguagem de programação
        description: Descrição do serviço
        requirements: Lista de requisitos

    Returns:
        Código gerado como string
    """
    timestamp = datetime.utcnow().isoformat()

    if language == "python":
        return f'''# {service_name} - Generated by Neural Code Forge
# Generated at: {timestamp}
# Template-based generation (heuristic)

from fastapi import FastAPI, HTTPException
import structlog

logger = structlog.get_logger(__name__)
app = FastAPI(
    title="{service_name}",
    description="{description or "Generated service"}"
)

@app.get("/health")
async def health():
    """Health check endpoint."""
    return {{
        "status": "healthy",
        "service": "{service_name}",
        "timestamp": "{timestamp}"
    }}

@app.get("/")
async def root():
    """Root endpoint."""
    return {{
        "message": "Generated by Neural Code Forge",
        "service": "{service_name}"
    }}

@app.get("/info")
async def info():
    """Service information."""
    return {{
        "service": "{service_name}",
        "description": "{description}",
        "requirements": {requirements},
        "generated_at": "{timestamp}"
    }}

# Add your business logic here
'''

    elif language == "javascript" or language == "typescript":
        return '''// Generated by Neural Code Forge
// Express.js service

const express = require('express');
const app = express();

app.get('/health', (req, res) => {
  res.json({ status: 'healthy', service: 'SERVICE_NAME' });
});

app.get('/', (req, res) => {
  res.json({ message: 'Generated by Neural Code Forge' });
});

const PORT = process.env.PORT || 3000;
app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
'''
    else:
        # Fallback para Python
        return generate_code_heuristic(service_name, "python", description, requirements)
