# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import queen_agent_pb2 as queen__agent__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in queen_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueenAgentStub(object):
    """Serviço Queen Agent - Coordenador Estratégico
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStrategicDecision = channel.unary_unary(
                '/queen_agent.QueenAgent/GetStrategicDecision',
                request_serializer=queen__agent__pb2.GetStrategicDecisionRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.StrategicDecisionResponse.FromString,
                _registered_method=True)
        self.ListStrategicDecisions = channel.unary_unary(
                '/queen_agent.QueenAgent/ListStrategicDecisions',
                request_serializer=queen__agent__pb2.ListStrategicDecisionsRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.ListStrategicDecisionsResponse.FromString,
                _registered_method=True)
        self.GetSystemStatus = channel.unary_unary(
                '/queen_agent.QueenAgent/GetSystemStatus',
                request_serializer=queen__agent__pb2.GetSystemStatusRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.SystemStatusResponse.FromString,
                _registered_method=True)
        self.RequestExceptionApproval = channel.unary_unary(
                '/queen_agent.QueenAgent/RequestExceptionApproval',
                request_serializer=queen__agent__pb2.RequestExceptionRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.RequestExceptionResponse.FromString,
                _registered_method=True)
        self.ApproveException = channel.unary_unary(
                '/queen_agent.QueenAgent/ApproveException',
                request_serializer=queen__agent__pb2.ApproveExceptionRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.ApproveExceptionResponse.FromString,
                _registered_method=True)
        self.RejectException = channel.unary_unary(
                '/queen_agent.QueenAgent/RejectException',
                request_serializer=queen__agent__pb2.RejectExceptionRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.RejectExceptionResponse.FromString,
                _registered_method=True)
        self.GetActiveConflicts = channel.unary_unary(
                '/queen_agent.QueenAgent/GetActiveConflicts',
                request_serializer=queen__agent__pb2.GetActiveConflictsRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.GetActiveConflictsResponse.FromString,
                _registered_method=True)
        self.SubmitInsight = channel.unary_unary(
                '/queen_agent.QueenAgent/SubmitInsight',
                request_serializer=queen__agent__pb2.SubmitInsightRequest.SerializeToString,
                response_deserializer=queen__agent__pb2.SubmitInsightResponse.FromString,
                _registered_method=True)


class QueenAgentServicer(object):
    """Serviço Queen Agent - Coordenador Estratégico
    """

    def GetStrategicDecision(self, request, context):
        """Buscar decisão estratégica por ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListStrategicDecisions(self, request, context):
        """Listar decisões estratégicas recentes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSystemStatus(self, request, context):
        """Obter status geral do sistema
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestExceptionApproval(self, request, context):
        """Solicitar aprovação de exceção
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveException(self, request, context):
        """Aprovar exceção
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RejectException(self, request, context):
        """Rejeitar exceção
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetActiveConflicts(self, request, context):
        """Obter conflitos ativos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInsight(self, request, context):
        """Submeter insight de Analyst Agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueenAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStrategicDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStrategicDecision,
                    request_deserializer=queen__agent__pb2.GetStrategicDecisionRequest.FromString,
                    response_serializer=queen__agent__pb2.StrategicDecisionResponse.SerializeToString,
            ),
            'ListStrategicDecisions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListStrategicDecisions,
                    request_deserializer=queen__agent__pb2.ListStrategicDecisionsRequest.FromString,
                    response_serializer=queen__agent__pb2.ListStrategicDecisionsResponse.SerializeToString,
            ),
            'GetSystemStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSystemStatus,
                    request_deserializer=queen__agent__pb2.GetSystemStatusRequest.FromString,
                    response_serializer=queen__agent__pb2.SystemStatusResponse.SerializeToString,
            ),
            'RequestExceptionApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestExceptionApproval,
                    request_deserializer=queen__agent__pb2.RequestExceptionRequest.FromString,
                    response_serializer=queen__agent__pb2.RequestExceptionResponse.SerializeToString,
            ),
            'ApproveException': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveException,
                    request_deserializer=queen__agent__pb2.ApproveExceptionRequest.FromString,
                    response_serializer=queen__agent__pb2.ApproveExceptionResponse.SerializeToString,
            ),
            'RejectException': grpc.unary_unary_rpc_method_handler(
                    servicer.RejectException,
                    request_deserializer=queen__agent__pb2.RejectExceptionRequest.FromString,
                    response_serializer=queen__agent__pb2.RejectExceptionResponse.SerializeToString,
            ),
            'GetActiveConflicts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveConflicts,
                    request_deserializer=queen__agent__pb2.GetActiveConflictsRequest.FromString,
                    response_serializer=queen__agent__pb2.GetActiveConflictsResponse.SerializeToString,
            ),
            'SubmitInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInsight,
                    request_deserializer=queen__agent__pb2.SubmitInsightRequest.FromString,
                    response_serializer=queen__agent__pb2.SubmitInsightResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'queen_agent.QueenAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('queen_agent.QueenAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueenAgent(object):
    """Serviço Queen Agent - Coordenador Estratégico
    """

    @staticmethod
    def GetStrategicDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/GetStrategicDecision',
            queen__agent__pb2.GetStrategicDecisionRequest.SerializeToString,
            queen__agent__pb2.StrategicDecisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListStrategicDecisions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/ListStrategicDecisions',
            queen__agent__pb2.ListStrategicDecisionsRequest.SerializeToString,
            queen__agent__pb2.ListStrategicDecisionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSystemStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/GetSystemStatus',
            queen__agent__pb2.GetSystemStatusRequest.SerializeToString,
            queen__agent__pb2.SystemStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestExceptionApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/RequestExceptionApproval',
            queen__agent__pb2.RequestExceptionRequest.SerializeToString,
            queen__agent__pb2.RequestExceptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveException(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/ApproveException',
            queen__agent__pb2.ApproveExceptionRequest.SerializeToString,
            queen__agent__pb2.ApproveExceptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RejectException(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/RejectException',
            queen__agent__pb2.RejectExceptionRequest.SerializeToString,
            queen__agent__pb2.RejectExceptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetActiveConflicts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/GetActiveConflicts',
            queen__agent__pb2.GetActiveConflictsRequest.SerializeToString,
            queen__agent__pb2.GetActiveConflictsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/queen_agent.QueenAgent/SubmitInsight',
            queen__agent__pb2.SubmitInsightRequest.SerializeToString,
            queen__agent__pb2.SubmitInsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
