apiVersion: v1
kind: Service
metadata:
  name: {{ include "optimizer-agents.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "optimizer-agents.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: grpc
    port: {{ .Values.service.ports.grpc }}
    targetPort: grpc
    protocol: TCP
  - name: http
    port: {{ .Values.service.ports.http }}
    targetPort: http
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "optimizer-agents.selectorLabels" . | nindent 4 }}
