apiVersion: v1
kind: Service
metadata:
  name: {{ include "doc-ingestion.fullname" . }}
  labels:
    {{- include "doc-ingestion.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.observability.enabled }}
    - port: {{ .Values.observability.prometheus.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "doc-ingestion.selectorLabels" . | nindent 4 }}
