global:
  proxy:
    autoInject: enabled
    logLevel: info
  tracer:
    zipkin:
      address: otel-collector.observability.svc.cluster.local:9411

istiod:
  replicaCount: 2
  env:
    PILOT_ENABLE_WORKLOAD_ENTRY_AUTOREGISTRATION: true
    PILOT_TRACE_SAMPLING: 100

meshConfig:
  mtls:
    mode: PERMISSIVE
  enablePrometheusMerge: true

base:
  enabled: true

istiod:
  enabled: true

gateway:
  enabled: true
  name: istio-ingressgateway
  service:
    type: LoadBalancer
  ports:
  - name: http2
    port: 80
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443