apiVersion: v1
kind: Namespace
metadata:
  name: neural-hive-orchestration
---
apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: neural-hive-orchestration
spec:
  type: ExternalName
  externalName: opa.neural-hive.svc.cluster.local
  ports:
  - port: 8181
