# Grafana Values Template
# Generated by Terraform for Neural Hive-Mind Observability Stack

# Global configuration
global:
  domain: "${domain}"
  environment: "${environment}"

# Feature flags para datasources opcionais
featureFlags:
  enableLoki: ${enable_loki}
  enableTempo: ${enable_tempo}

# Configuração do Grafana
grafana:
  enabled: true

  # Image
  image:
    repository: grafana/grafana
    tag: "10.2.0"
    pullPolicy: IfNotPresent

  # Replicas for HA
  replicas: ${replicas}

  # Admin credentials - use existing secret
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
    username: admin
    # Password is managed via Kubernetes secret, not stored in Terraform for security

  # Resources
  resources:
    limits:
      cpu: "${resources.limits.cpu}"
      memory: "${resources.limits.memory}"
    requests:
      cpu: "${resources.requests.cpu}"
      memory: "${resources.requests.memory}"

  # Persistence
  persistence:
    enabled: true
    storageClassName: ${storage_class}
    size: ${storage_size}
    accessModes:
    - ReadWriteOnce

  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
    annotations:
      neural.hive/component: "dashboard-visualization"
      neural.hive/layer: "observabilidade"

  # Security Context
  securityContext:
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472

  # Pod Security Context
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
    fsGroup: 472
    %{ if security_enabled ~}
    seccompProfile:
      type: RuntimeDefault
    %{ endif ~}

  # Anti-affinity para HA
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - grafana
          topologyKey: kubernetes.io/hostname

  # Configuração do Grafana
  grafana.ini:
    # Server settings
    server:
      domain: "grafana.${domain}"
      root_url: "https://grafana.${domain}"
      serve_from_sub_path: false
      enable_gzip: true

    # Analytics (desabilitado para privacidade)
    analytics:
      reporting_enabled: false
      check_for_updates: false
      google_analytics_ua_id: ""
      google_tag_manager_id: ""

    # Security
    security:
      disable_gravatar: true
      cookie_secure: true
      cookie_samesite: "strict"
      content_type_protection: true
      x_content_type_options: true
      x_xss_protection: true
      strict_transport_security: true
      strict_transport_security_max_age: 86400
      strict_transport_security_preload: true
      strict_transport_security_subdomains: true
      x_frame_options: "deny"

    # Auth
    auth:
      disable_login_form: false
      disable_signout_menu: false
      oauth_auto_login: false

    # Auth Anonymous (desabilitado)
    auth.anonymous:
      enabled: false

    # Logging
    log:
      mode: "console"
      level: "info"
      filters: "rendering:debug"

    # Metrics
    metrics:
      enabled: true
      basic_auth_username: ""
      basic_auth_password: ""

    # Feature toggles
    feature_toggles:
      enable: "alertingPreview,live,publicDashboards,scenes,correlations,datasourceOnboarding,cloudWatchCrossAccountQuerying"

    # Unified alerting
    alerting:
      enabled: true
      execute_alerts: true
      error_or_timeout: "alerting"
      nodata_or_nullvalues: "no_data"
      concurrent_render_limit: 5

    # Live settings
    live:
      allowed_origins: "*"
      max_connections: 100

    # Database (using SQLite for simplicity, PostgreSQL recommended for production)
    database:
      type: sqlite3
      path: /var/lib/grafana/grafana.db
      cache_mode: private

    # Session
    session:
      provider: memory

    # Paths
    paths:
      data: /var/lib/grafana
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning

  # Environment variables
  envFromSecret: grafana-admin-credentials
  env:
    GF_EXPLORE_ENABLED: "true"
    GF_SECURITY_DISABLE_GRAVATAR: "true"
    GF_ANALYTICS_REPORTING_ENABLED: "false"
    GF_FEATURE_TOGGLES_ENABLE: "alertingPreview,live,publicDashboards"

  # Data sources automáticos
  sidecar:
    datasources:
      enabled: true
      label: "grafana_datasource"
      labelValue: "1"
      folder: /tmp/dashboards
      defaultDatasourceEnabled: true
      searchNamespace: ALL

    dashboards:
      enabled: true
      label: "grafana_dashboard"
      labelValue: "1"
      folder: /tmp/dashboards
      provider:
        allowUiUpdates: true
        foldersFromFilesStructure: true

  # Plugins para instalar
  plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel
  - natel-discrete-panel
  - vonage-status-panel
  - grafana-polystat-panel
  - petrslavotinek-carpetplot-panel
  - briangann-gauge-panel
  - grafana-simple-json-datasource

  # Configurações de data sources
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      # Prometheus - primary metrics source
      - name: Prometheus
        type: prometheus
        uid: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.observability.svc.cluster.local:9090
        isDefault: true
        jsonData:
          httpMethod: POST
          exemplarTraceIdDestinations:
          - name: trace_id
            datasourceUid: jaeger
        editable: true

      # Jaeger - distributed tracing
      - name: Jaeger
        type: jaeger
        uid: jaeger
        access: proxy
        url: http://jaeger-query.observability.svc.cluster.local:16686
        jsonData:
          %{ if enable_loki ~}
          tracesToLogs:
            datasourceUid: loki
            tags: [{ key: 'service.name', value: 'service' }]
          %{ endif ~}
          nodeGraph:
            enabled: true
        editable: true

      %{ if enable_loki ~}
      # Loki - logs aggregation
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://loki-gateway.observability.svc.cluster.local
        jsonData:
          maxLines: 1000
          derivedFields:
          - datasourceUid: jaeger
            matcherRegex: "trace_id=(\\w+)"
            name: TraceID
            url: "$${__value.raw}"
            urlDisplayLabel: 'View in Jaeger'
        editable: true
      %{ endif ~}

      %{ if enable_tempo ~}
      # Tempo - distributed tracing
      - name: Tempo
        type: tempo
        uid: tempo
        access: proxy
        url: http://tempo-query-frontend.observability.svc.cluster.local:3200
        jsonData:
          %{ if enable_loki ~}
          tracesToLogs:
            datasourceUid: loki
            tags: ['job', 'instance', 'pod', 'namespace']
          %{ endif ~}
          nodeGraph:
            enabled: true
        editable: true
      %{ endif ~}

      # TestData para desenvolvimento
      - name: TestData
        type: testdata
        uid: testdata
        access: proxy
        editable: true

  # Configurações de dashboards
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'neural-hive-overview'
        orgId: 1
        folder: 'Neural Hive-Mind'
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/neural-hive-overview

      - name: 'fluxos-operacionais'
        orgId: 1
        folder: 'Fluxos Operacionais'
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/fluxos

      - name: 'infrastructure'
        orgId: 1
        folder: 'Infrastructure'
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/infrastructure

      - name: 'slos'
        orgId: 1
        folder: 'SLOs & Error Budgets'
        type: file
        disableDeletion: false
        allowUiUpdates: true
        options:
          path: /var/lib/grafana/dashboards/slos

  # RBAC
  rbac:
    create: true
    pspEnabled: false

  # Service Account
  serviceAccount:
    create: true
    autoMount: true
    annotations:
      neural.hive/component: "grafana"

  # Network Policy
  networkPolicy:
    enabled: true
    allowExternal: true
    explicitNamespacesSelector: {}
    ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: observability
      - namespaceSelector:
          matchLabels:
            name: neural-hive
      ports:
      - port: 3000
        protocol: TCP

  # Health checks
  livenessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 30
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /api/health
      port: 3000
    initialDelaySeconds: 30
    periodSeconds: 5
    timeoutSeconds: 10
    failureThreshold: 3
    successThreshold: 1

  # Ingress configuration
  ingress:
    enabled: ${enable_ingress}
    %{ if enable_ingress ~}
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
    - host: "grafana.${domain}"
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: grafana-tls
      hosts:
      - "grafana.${domain}"
    %{ endif ~}

  # Monitoring
  serviceMonitor:
    enabled: true
    labels:
      neural.hive/metrics: "enabled"
    interval: 30s
    scrapeTimeout: 10s
    path: /metrics

# Neural Hive annotations
podAnnotations:
  neural.hive/component: "grafana"
  neural.hive/layer: "observabilidade"

podLabels:
  neural.hive/component: "grafana"
  neural.hive/layer: "observabilidade"