# Jaeger Values Template
# Generated by Terraform for Neural Hive-Mind Observability Stack

# Configuração global
global:
  imageRegistry: ""

# Tags de imagens
provisionDataStore:
  cassandra: false
  elasticsearch: true

# Estratégia de deployment
strategy: production

# Storage backend
storage:
  type: "${storage_type}"
  options:
    es:
      server-urls: http://elasticsearch:9200
      index-prefix: jaeger
      username: ""
      password: ""
      version: 7
      create-index-templates: true

# Jaeger Agent
agent:
  enabled: true
  image: jaegertracing/jaeger-agent

  # Configuração de recursos
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

  # DaemonSet para todos os nós
  daemonSet:
    enabled: true

  # Configurações específicas do agent
  cmdlineParams:
    reporter.grpc.host-port: "jaeger-collector:14250"
    reporter.type: "grpc"

# Jaeger Collector
collector:
  enabled: true
  image: jaegertracing/jaeger-collector

  # Réplicas
  replicaCount: 2

  # Configuração de recursos
  resources:
    requests:
      memory: "${resources.collector.requests.memory}"
      cpu: "${resources.collector.requests.cpu}"
    limits:
      memory: "${resources.collector.limits.memory}"
      cpu: "${resources.collector.limits.cpu}"

  # Service configuration
  service:
    type: ClusterIP
    grpc:
      port: 14250
    http:
      port: 14268
    zipkin:
      port: 9411

  # Configuração de segurança
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000

  # Environment variables
  env:
    - name: SPAN_STORAGE_TYPE
      value: "${storage_type}"

  # Configuração de sampling
  cmdlineParams:
    collector.num-workers: 100
    collector.queue-size: 2000

  # Affinity para distribuir collectors
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: collector
          topologyKey: kubernetes.io/hostname

# Jaeger Query (UI)
query:
  enabled: true
  image: jaegertracing/jaeger-query

  # Réplicas
  replicaCount: 1

  # Configuração de recursos
  resources:
    requests:
      memory: "${resources.query.requests.memory}"
      cpu: "${resources.query.requests.cpu}"
    limits:
      memory: "${resources.query.limits.memory}"
      cpu: "${resources.query.limits.cpu}"

  # Service configuration
  service:
    type: ClusterIP
    port: 80
    targetPort: 16686

  # Ingress configuration
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
    - host: jaeger.neural-hive.local
      paths:
      - path: /
        pathType: Prefix
    tls: []

  # Environment variables
  env:
    - name: SPAN_STORAGE_TYPE
      value: "${storage_type}"

  # Query configuration
  cmdlineParams:
    query.static-files: /go/jaeger-ui/
    query.ui-config: /tmp/ui.json

  # UI configuration
  config:
    ui:
      dependencies:
        dagMaxNumServices: 200
        menuEnabled: true
      archiveEnabled: true
      tracking:
        gaID: null
        trackErrors: true

# Elasticsearch (se usado como backend)
%{ if storage_type == "elasticsearch" ~}
elasticsearch:
  enabled: true

  # Cluster configuration
  clusterName: "jaeger-elasticsearch"

  # Master nodes
  master:
    enabled: true
    replicas: 3

    # Resources
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

    # Persistence
    persistence:
      enabled: true
      storageClassName: "${storage_class}"
      size: "10Gi"

  # Data nodes
  data:
    enabled: true
    replicas: 2

    # Resources
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    # Persistence
    persistence:
      enabled: true
      storageClassName: "${storage_class}"
      size: "50Gi"

  # Client/Coordinating nodes
  client:
    enabled: true
    replicas: 1

    # Resources
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "1Gi"
        cpu: "500m"

  # Elasticsearch configuration
  esConfig:
    elasticsearch.yml: |
      cluster.name: jaeger-elasticsearch
      node.data: $${NODE_DATA:true}
      node.master: $${NODE_MASTER:true}
      node.ingest: $${NODE_INGEST:true}
      network.host: 0.0.0.0
      bootstrap.memory_lock: false
      discovery.seed_hosts: "jaeger-elasticsearch-master"
      cluster.initial_master_nodes: "jaeger-elasticsearch-master-0,jaeger-elasticsearch-master-1,jaeger-elasticsearch-master-2"

      # Index lifecycle management
      xpack.ilm.enabled: true

      # Security
      xpack.security.enabled: false

      # Performance
      thread_pool.bulk.queue_size: 1000
      thread_pool.search.queue_size: 1000

      # Jaeger specific settings
      index.number_of_shards: 1
      index.number_of_replicas: 1
      index.refresh_interval: 1s

# Index cleaner para limpeza automática
esIndexCleaner:
  enabled: true
  image: jaegertracing/jaeger-es-index-cleaner

  # Schedule para limpeza (diário às 2:00 AM)
  schedule: "0 2 * * *"

  # Retenção de dados em dias
  numberOfDays: ${retention_days}

  # Resources
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"

%{ endif ~}

# Cassandra (se usado como backend)
%{ if storage_type == "cassandra" ~}
cassandra:
  enabled: true

  # Cluster configuration
  cluster:
    name: jaeger-cassandra
    replicaCount: 3

  # Resources
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "4Gi"
      cpu: "2000m"

  # Persistence
  persistence:
    enabled: true
    storageClassName: "${storage_class}"
    size: "100Gi"

  # Configuration
  config:
    cluster_size: 3
    seeds: "jaeger-cassandra-0.jaeger-cassandra.observability.svc.cluster.local"

    # Performance tuning
    max_heap_size: "2G"
    heap_newsize: "400M"

    # JVM options
    jvm_opts:
      - "-Xms2G"
      - "-Xmx2G"
      - "-XX:+UnlockExperimentalVMOptions"
      - "-XX:+UseCGroupMemoryLimitForHeap"

# Schema job para criação de tabelas
cassandraSchema:
  enabled: true
  image: jaegertracing/jaeger-cassandra-schema

  # Job configuration
  mode: "prod"
  datacenter: "dc1"

  # Keyspace configuration
  keyspace: "jaeger_v1_dc1"
  replicationFactor: 1

%{ endif ~}

# Service Mesh Integration
serviceMesh:
  # Istio integration
  istio:
    enabled: true
    # Inject Jaeger agent as sidecar
    sidecar: false
    # Use daemonset agent instead
    agent: true

# Hot R.O.D. demo application (desabilitado em produção)
hotrod:
  enabled: false

# Labels globais
commonLabels:
  neural.hive/component: "tracing"
  neural.hive/layer: "observabilidade"

# Annotations globais
commonAnnotations:
  neural.hive/version: "1.0.0"

# Security context global
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Node affinity para nós de observabilidade
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: "node-role.kubernetes.io/observability"
          operator: "In"
          values: ["true"]

# Tolerations para nós dedicados
tolerations:
- key: "observability"
  operator: "Equal"
  value: "true"
  effect: "NoSchedule"