# Jaeger Values Template (Chart v3.0.10)
# Generated by Terraform for Neural Hive-Mind Observability Stack

# Global configuration
global:
  imageRegistry: ""

# Deployment strategy: allinone (development) or production
%{ if deployment_strategy == "allinone" ~}
# All-in-One deployment for development
allInOne:
  enabled: true
  image:
    repository: jaegertracing/all-in-one
    tag: "1.50.0"
    pullPolicy: IfNotPresent

  # Storage configuration for all-in-one
  %{ if storage_type == "memory" ~}
  args:
    - "--memory.max-traces"
    - "50000"
  %{ endif ~}
  %{ if storage_type == "badger" ~}
  args:
    - "--badger.ephemeral=false"
    - "--badger.directory-key=/badger/key"
    - "--badger.directory-value=/badger/data"
    - "--badger.span-store-ttl=168h"

  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: "10Gi"
    accessModes:
      - ReadWriteOnce
  %{ endif ~}

  # Resources
  resources:
    limits:
      cpu: "${resources.collector.limits.cpu}"
      memory: "${resources.collector.limits.memory}"
    requests:
      cpu: "${resources.collector.requests.cpu}"
      memory: "${resources.collector.requests.memory}"

  # Service configuration
  service:
    type: ClusterIP
    ports:
      - name: jaeger-agent-thrift-compact
        port: 6831
        protocol: UDP
        targetPort: 6831
      - name: jaeger-agent-thrift-binary
        port: 6832
        protocol: UDP
        targetPort: 6832
      - name: jaeger-query-http
        port: 16686
        protocol: TCP
        targetPort: 16686
      - name: jaeger-collector-otlp-grpc
        port: 14250
        protocol: TCP
        targetPort: 14250
      %{ if enable_otlp ~}
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: otlp-http
        port: 4318
        protocol: TCP
        targetPort: 4318
      %{ endif ~}

  # Ingress
  ingress:
    enabled: false

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "jaeger-allinone"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "jaeger-allinone"
    neural.hive/layer: "observabilidade"

%{ else ~}
# Production deployment with separate components
collector:
  enabled: true
  image:
    repository: jaegertracing/jaeger-collector
    tag: "1.50.0"
    pullPolicy: IfNotPresent

  # Replicas for HA
  replicaCount: 2

  # Resources
  resources:
    limits:
      cpu: "${resources.collector.limits.cpu}"
      memory: "${resources.collector.limits.memory}"
    requests:
      cpu: "${resources.collector.requests.cpu}"
      memory: "${resources.collector.requests.memory}"

  # Service configuration
  service:
    type: ClusterIP
    ports:
      - name: jaeger-collector-tchannel
        port: 14267
        protocol: TCP
        targetPort: 14267
      - name: jaeger-collector-http
        port: 14268
        protocol: TCP
        targetPort: 14268
      - name: jaeger-collector-grpc
        port: 14250
        protocol: TCP
        targetPort: 14250
      %{ if enable_otlp ~}
      - name: otlp-grpc
        port: 4317
        protocol: TCP
        targetPort: 4317
      - name: otlp-http
        port: 4318
        protocol: TCP
        targetPort: 4318
      %{ endif ~}

  # Configuration for collector
  config:
    %{ if enable_otlp ~}
    receiver:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    %{ endif ~}

    %{ if storage_type == "elasticsearch" ~}
    span-storage:
      type: elasticsearch
      elasticsearch:
        server-urls: http://elasticsearch:9200
        index-prefix: jaeger
        username: ""
        password: ""
        version: 7
        create-index-templates: true
        num-shards: 5
        num-replicas: 1
        max-span-age: ${retention_days * 24}h
    %{ endif ~}

    %{ if storage_type == "badger" ~}
    span-storage:
      type: badger
      badger:
        ephemeral: false
        directory-key: /badger/key
        directory-value: /badger/data
        span-store-ttl: ${retention_days * 24}h
    %{ endif ~}

  # Persistence for badger
  %{ if storage_type == "badger" ~}
  persistence:
    enabled: true
    storageClass: "${storage_class}"
    size: "20Gi"
    accessModes:
      - ReadWriteOnce
  %{ endif ~}

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "jaeger-collector"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "jaeger-collector"
    neural.hive/layer: "observabilidade"

# Jaeger Query service
query:
  enabled: true
  image:
    repository: jaegertracing/jaeger-query
    tag: "1.50.0"
    pullPolicy: IfNotPresent

  # Replicas for HA
  replicaCount: 2

  # Resources
  resources:
    limits:
      cpu: "${resources.query.limits.cpu}"
      memory: "${resources.query.limits.memory}"
    requests:
      cpu: "${resources.query.requests.cpu}"
      memory: "${resources.query.requests.memory}"

  # Service configuration
  service:
    type: ClusterIP
    port: 16686
    targetPort: 16686

  # Configuration
  config:
    %{ if storage_type == "elasticsearch" ~}
    span-storage:
      type: elasticsearch
      elasticsearch:
        server-urls: http://elasticsearch:9200
        index-prefix: jaeger
        username: ""
        password: ""
        version: 7
        max-span-age: ${retention_days * 24}h
    %{ endif ~}

    %{ if storage_type == "badger" ~}
    span-storage:
      type: badger
      badger:
        ephemeral: false
        directory-key: /badger/key
        directory-value: /badger/data
        span-store-ttl: ${retention_days * 24}h
    %{ endif ~}

  # Ingress
  ingress:
    enabled: false

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "jaeger-query"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "jaeger-query"
    neural.hive/layer: "observabilidade"

# Jaeger Agent (optional for production)
agent:
  enabled: true
  image:
    repository: jaegertracing/jaeger-agent
    tag: "1.50.0"
    pullPolicy: IfNotPresent

  # Daemonset deployment
  daemonset:
    useHostPort: true

  # Resources
  resources:
    limits:
      cpu: "200m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "jaeger-agent"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "jaeger-agent"
    neural.hive/layer: "observabilidade"

%{ endif ~}

# Sampling strategies
%{ if length(sampling_strategies.per_service_strategies) > 0 ~}
sampling:
  strategies: |
    {
      "default_strategy": {
        "type": "${sampling_strategies.default_strategy.type}",
        "param": ${sampling_strategies.default_strategy.param}
      },
      "per_service_strategies": [
        %{ for strategy in sampling_strategies.per_service_strategies ~}
        {
          "service": "${strategy.service}",
          "type": "${strategy.type}",
          "param": ${strategy.param}
        }%{ if strategy != sampling_strategies.per_service_strategies[length(sampling_strategies.per_service_strategies) - 1] ~},%{ endif ~}
        %{ endfor ~}
      ]
    }
%{ endif ~}

# ServiceAccount
serviceAccount:
  create: true
  annotations:
    neural.hive/component: "jaeger"

# RBAC
rbac:
  create: true

# Security Context
securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  fsGroup: 10001

# Network Policy
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: neural-hive
      - namespaceSelector:
          matchLabels:
            name: observability
      ports:
      - port: 16686
        protocol: TCP
      - port: 14250
        protocol: TCP
      - port: 6831
        protocol: UDP
      - port: 6832
        protocol: UDP
      %{ if enable_otlp ~}
      - port: 4317
        protocol: TCP
      - port: 4318
        protocol: TCP
      %{ endif ~}

# ServiceMonitor for Prometheus
serviceMonitor:
  enabled: true
  labels:
    neural.hive/metrics: "enabled"
  interval: 30s
  scrapeTimeout: 10s