# Loki Stack Values Template
# Generated by Terraform for Neural Hive-Mind Observability Stack

# Loki configuration
loki:
  enabled: true

  # Image configuration
  image:
    repository: grafana/loki
    tag: "2.9.2"
    pullPolicy: IfNotPresent

  # Resources
  resources:
    limits:
      cpu: "${resources.loki.limits.cpu}"
      memory: "${resources.loki.limits.memory}"
    requests:
      cpu: "${resources.loki.requests.cpu}"
      memory: "${resources.loki.requests.memory}"

  # Persistence
  persistence:
    enabled: true
    storageClassName: "${storage_class}"
    size: "${storage_size}"
    accessModes:
      - ReadWriteOnce

  # Configuration
  config:
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9096
      log_level: info

    common:
      path_prefix: /loki
      storage:
        filesystem:
          chunks_directory: /loki/chunks
          rules_directory: /loki/rules
      replication_factor: 1
      ring:
        kvstore:
          store: inmemory

    query_range:
      results_cache:
        cache:
          embedded_cache:
            enabled: true
            max_size_mb: 100

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/boltdb-shipper-active
        cache_location: /loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: /loki/chunks

    limits_config:
      reject_old_samples: true
      reject_old_samples_max_age: 168h  # 7 days
      ingestion_rate_mb: 16
      ingestion_burst_size_mb: 32
      per_stream_rate_limit: 3MB
      per_stream_rate_limit_burst: 15MB
      max_query_parallelism: 32
      max_streams_per_user: 10000
      max_global_streams_per_user: 5000
      retention_period: ${retention_days * 24}h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: true
      retention_period: ${retention_days * 24}h

    ruler:
      storage:
        type: local
        local:
          directory: /loki/rules
      rule_path: /loki/rules
      alertmanager_url: http://prometheus-kube-prometheus-alertmanager:9093
      ring:
        kvstore:
          store: inmemory
      enable_api: true

  # Service configuration
  service:
    type: ClusterIP
    port: 3100
    targetPort: 3100
    annotations:
      neural.hive/component: "loki"
      neural.hive/layer: "observabilidade"

  # Security Context
  securityContext:
    runAsNonRoot: true
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "loki"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "loki"
    neural.hive/layer: "observabilidade"

  # ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: true
    labels:
      neural.hive/metrics: "enabled"
    interval: 30s
    scrapeTimeout: 10s

# Promtail configuration (log collector)
promtail:
  enabled: ${enable_promtail}

  # Image configuration
  image:
    repository: grafana/promtail
    tag: "2.9.2"
    pullPolicy: IfNotPresent

  # Resources
  resources:
    limits:
      cpu: "${resources.promtail.limits.cpu}"
      memory: "${resources.promtail.limits.memory}"
    requests:
      cpu: "${resources.promtail.requests.cpu}"
      memory: "${resources.promtail.requests.memory}"

  # Configuration
  config:
    server:
      http_listen_port: 3101

    clients:
      - url: http://loki:3100/loki/api/v1/push

    positions:
      filename: /tmp/positions.yaml

    target_config:
      sync_period: 10s

    scrape_configs:
    # Neural Hive-Mind services
    - job_name: neural-hive-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - source_labels: [__meta_kubernetes_pod_label_neural_hive_component]
          target_label: neural_hive_component
        - source_labels: [__meta_kubernetes_pod_label_neural_hive_layer]
          target_label: neural_hive_layer
        - source_labels: [__meta_kubernetes_pod_label_neural_hive_domain]
          target_label: neural_hive_domain
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node

      # Pipeline stages for correlation
      pipeline_stages:
        - cri: {}
        - regex:
            expression: '.*intent_id=(?P<intent_id>[a-zA-Z0-9\-]+).*'
        - regex:
            expression: '.*plan_id=(?P<plan_id>[a-zA-Z0-9\-]+).*'
        - regex:
            expression: '.*user_id=(?P<user_id>[a-zA-Z0-9\-]+).*'
        - regex:
            expression: '.*trace_id=(?P<trace_id>[a-fA-F0-9]{32}).*'
        - labels:
            intent_id: intent_id
            plan_id: plan_id
            user_id: user_id
            trace_id: trace_id
        - output:
            source: message

    # System containers
    - job_name: kubernetes-pods
      kubernetes_sd_configs:
        - role: pod
      relabel_configs:
        - action: keep
          regex: true
          source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        - source_labels: [__meta_kubernetes_pod_name]
          target_label: pod
        - source_labels: [__meta_kubernetes_namespace]
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_container_name]
          target_label: container
        - source_labels: [__meta_kubernetes_pod_node_name]
          target_label: node

  # Service Account
  serviceAccount:
    create: true
    annotations:
      neural.hive/component: "promtail"

  # RBAC for log collection
  rbac:
    create: true
    pspEnabled: false

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "promtail"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "promtail"
    neural.hive/layer: "observabilidade"

  # ServiceMonitor for Prometheus
  serviceMonitor:
    enabled: true
    labels:
      neural.hive/metrics: "enabled"
    interval: 30s
    scrapeTimeout: 10s

# Fluent Bit (alternative to Promtail)
fluent-bit:
  enabled: ${enable_fluent_bit}

  # Image configuration
  image:
    repository: fluent/fluent-bit
    tag: "2.1.10"
    pullPolicy: IfNotPresent

  # Resources
  resources:
    limits:
      cpu: "${resources.promtail.limits.cpu}"
      memory: "${resources.promtail.limits.memory}"
    requests:
      cpu: "${resources.promtail.requests.cpu}"
      memory: "${resources.promtail.requests.memory}"

  # Configuration
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush 1
          Log_Level info
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port 2020
          Health_Check On
          storage.metrics on

    inputs: |
      [INPUT]
          Name tail
          Path /var/log/containers/*neural-hive*.log
          multiline.parser cri
          Tag neural.hive.*
          Mem_Buf_Limit 50MB
          Skip_Long_Lines On
          Refresh_Interval 10

      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          multiline.parser cri
          Tag kubernetes.*
          Exclude_Path /var/log/containers/*neural-hive*.log
          Mem_Buf_Limit 20MB
          Skip_Long_Lines On
          Refresh_Interval 10

    filters: |
      [FILTER]
          Name kubernetes
          Match neural.hive.*
          Kube_URL https://kubernetes.default.svc:443
          Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
          Kube_Tag_Prefix neural.hive.
          Merge_Log On
          Keep_Log Off
          K8S-Logging.Parser On
          K8S-Logging.Exclude On
          Annotations Off
          Labels On

      [FILTER]
          Name modify
          Match neural.hive.*
          Add source fluent-bit
          Add cluster neural-hive-cluster

    outputs: |
      [OUTPUT]
          Name loki
          Match neural.hive.*
          Host loki
          Port 3100
          Labels cluster=neural-hive-cluster, source=fluent-bit
          Label_map_path /fluent-bit/etc/labelmap.conf
          Line_format json
          Remove_keys kubernetes,stream
          Auto_Kubernetes_Labels on

  # Neural Hive annotations
  podAnnotations:
    neural.hive/component: "fluent-bit"
    neural.hive/layer: "observabilidade"

  podLabels:
    neural.hive/component: "fluent-bit"
    neural.hive/layer: "observabilidade"

# Gateway service (if needed)
gateway:
  enabled: false

# Grafana agent mode (disabled - using dedicated Grafana)
grafana:
  enabled: false

# Test framework
test:
  enabled: false

# RBAC
rbac:
  create: true
  pspEnabled: false

# Network Policy
networkPolicy:
  enabled: true
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: neural-hive
      - namespaceSelector:
          matchLabels:
            name: observability
      ports:
      - port: 3100
        protocol: TCP
      - port: 3101
        protocol: TCP