# Prometheus Stack Values Template
# Generated by Terraform for Neural Hive-Mind Observability Stack

global:
  imageRegistry: ""
  imagePullSecrets: []

# Configuração do Prometheus Server
prometheus:
  prometheusSpec:
    # Retenção de dados
    retention: "${retention_days}d"
    retentionSize: "50GiB"

    # Storage persistente
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: "${storage_class}"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "${storage_size}"

    # Configuração de recursos
    resources:
      requests:
        memory: "2Gi"
        cpu: "1000m"
      limits:
        memory: "4Gi"
        cpu: "2000m"

    # Configuração de scraping
    scrapeInterval: "15s"
    evaluationInterval: "15s"

    # External labels para federação
    externalLabels:
      cluster: "neural-hive-main"
      environment: "production"
      neural_hive_cluster: "main"

    # Configuração de rules
    ruleSelector:
      matchLabels:
        prometheus: "kube-prometheus"

    # ServiceMonitor selector
    serviceMonitorSelector:
      matchLabels:
        prometheus: "kube-prometheus"

    # PodMonitor selector
    podMonitorSelector:
      matchLabels:
        prometheus: "kube-prometheus"

    # Configuração de alerting
    alerting:
      alertmanagers:
      - namespace: observability
        name: alertmanager-operated
        port: web
        pathPrefix: /

    # Configuração de segurança
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      fsGroup: 2000

    # Configuração de tolerations para nós dedicados
    tolerations:
    - key: "observability"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"

    # Node affinity para nós de observabilidade
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
            - key: "node-role.kubernetes.io/observability"
              operator: "In"
              values: ["true"]

# Configuração do Grafana
grafana:
  enabled: true

  # Admin credentials
  adminPassword: "${grafana_admin_password}"

  # Configuração de storage
  persistence:
    enabled: true
    storageClassName: "${storage_class}"
    size: "10Gi"

  # Configuração de recursos
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

  # Datasources
  sidecar:
    datasources:
      enabled: true
      searchNamespace: "ALL"

  # Dashboards
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: "ALL"
      folderAnnotation: "grafana_folder"
      provider:
        foldersFromFilesStructure: true

  # Configuração de acesso
  service:
    type: ClusterIP
    port: 80

  # Configuração de plugins
  plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel

# Configuração do AlertManager
alertmanager:
  alertmanagerSpec:
    # Storage
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: "${storage_class}"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: "5Gi"

    # Recursos
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"

    # Configuração de alerting
    config:
      global:
        smtp_smarthost: 'localhost:587'
        smtp_from: 'alertmanager@neural-hive.local'
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
        receiver: 'web.hook'
        routes:
        - match:
            severity: critical
          receiver: 'critical-alerts'
        - match:
            alertname: DeadMansSwitch
          receiver: 'null'
      receivers:
      - name: 'null'
      - name: 'web.hook'
        webhook_configs:
        - url: 'http://127.0.0.1:5001/'
      - name: 'critical-alerts'
        webhook_configs:
        - url: 'http://127.0.0.1:5001/critical'
          send_resolved: true

# Configuração do Node Exporter
nodeExporter:
  enabled: true

# Configuração do kube-state-metrics
kubeStateMetrics:
  enabled: true

# Configuração do Prometheus Operator
prometheusOperator:
  enabled: true

  # Recursos do operator
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

# Configuração específica para Thanos (se habilitado)
%{ if enable_thanos ~}
thanos:
  enabled: true
  objectStorageConfig:
    name: thanos-storage-config
    key: object-store.yaml
%{ endif ~}

# Configurações de networking
networking:
  serviceType: ClusterIP

# Configurações de segurança
podSecurityPolicy:
  enabled: false

# RBAC
rbac:
  create: true
  pspEnabled: false