"""
Unit tests para CodeForge Generation API.

Testa os endpoints /api/v1/generate:
- POST /api/v1/generate - cria requisição
- GET /api/v1/generate/{id} - status da requisição
- GET /api/v1/generate - listagem
"""

import pytest
import asyncio
from datetime import datetime
from fastapi.testclient import TestClient

from src.api.http_server import create_app
from src.api.generation_api import GENERATION_REQUESTS, _generate_code_heuristic


@pytest.fixture
def client():
    """Fixture para cliente de teste."""
    app = create_app()
    return TestClient(app)


@pytest.fixture(autouse=True)
def clear_requests():
    """Limpa requisições antes de cada teste."""
    GENERATION_REQUESTS.clear()
    yield
    GENERATION_REQUESTS.clear()


class TestCreateGenerationRequest:
    """Testes para POST /api/v1/generate"""

    def test_create_generation_request_202(self, client):
        """Testa criação de requisição com dados válidos."""
        payload = {
            "ticket_id": "test-ticket-001",
            "template_id": "microservice-python-v1",
            "parameters": {
                "service_name": "test-service",
                "language": "python"
            },
            "target_repo": "",
            "branch": "main"
        }

        response = client.post("/api/v1/generate", json=payload)

        assert response.status_code == 202
        data = response.json()
        assert "request_id" in data
        assert data["status"] == "queued"
        assert "message" in data

        # Verificar que foi armazenado
        request_id = data["request_id"]
        assert request_id in GENERATION_REQUESTS
        assert GENERATION_REQUESTS[request_id]["ticket_id"] == "test-ticket-001"

    def test_create_generation_request_missing_ticket_id_400(self, client):
        """Testa erro quando ticket_id não é fornecido."""
        payload = {
            "template_id": "microservice-python-v1",
            "parameters": {}
        }

        response = client.post("/api/v1/generate", json=payload)

        assert response.status_code == 400
        assert "ticket_id is required" in response.json()["detail"]

    def test_create_generation_request_missing_template_id_400(self, client):
        """Testa erro quando template_id não é fornecido."""
        payload = {
            "ticket_id": "test-ticket-002",
            "parameters": {}
        }

        response = client.post("/api/v1/generate", json=payload)

        assert response.status_code == 400
        assert "template_id is required" in response.json()["detail"]


class TestGetGenerationStatus:
    """Testes para GET /api/v1/generate/{request_id}"""

    def test_get_generation_status_queued(self, client):
        """Testa status imediatamente após criação (deve ser queued ou processing)."""
        # Criar requisição
        payload = {
            "ticket_id": "test-ticket-003",
            "template_id": "microservice-python-v1",
            "parameters": {"service_name": "test", "language": "python"}
        }
        create_response = client.post("/api/v1/generate", json=payload)
        request_id = create_response.json()["request_id"]

        # Obter status (imediatamente, pode ainda estar queued)
        response = client.get(f"/api/v1/generate/{request_id}")

        assert response.status_code == 200
        data = response.json()
        assert data["request_id"] == request_id
        assert data["status"] in ["queued", "processing", "completed"]
        assert "created_at" in data
        assert "updated_at" in data

    def test_get_generation_status_completed(self, client):
        """Testa status após processamento (aguardar completion)."""
        # Criar requisição
        payload = {
            "ticket_id": "test-ticket-004",
            "template_id": "microservice-python-v1",
            "parameters": {"service_name": "test", "language": "python"}
        }
        create_response = client.post("/api/v1/generate", json=payload)
        request_id = create_response.json()["request_id"]

        # Aguardar processamento
        asyncio.sleep(3)

        # Obter status
        response = client.get(f"/api/v1/generate/{request_id}")

        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "completed"
        assert len(data["artifacts"]) > 0
        assert data["artifacts"][0]["type"] == "code"
        assert "content_hash" in data["artifacts"][0]
        assert data["code_preview"] is not None
        assert "Generated by Neural Code Forge" in data["code_preview"]

    def test_get_generation_status_not_found_404(self, client):
        """Testa erro quando request_id não existe."""
        response = client.get("/api/v1/generate/nonexistent-id")

        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()


class TestListGenerationRequests:
    """Testes para GET /api/v1/generate"""

    def test_list_empty(self, client):
        """Testa listagem quando não há requisições."""
        response = client.get("/api/v1/generate")

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 0
        assert data["requests"] == []
        assert data["status_counts"] == {}

    def test_list_with_requests(self, client):
        """Testa listagem com requisições existentes."""
        # Criar duas requisições
        for i in range(2):
            payload = {
                "ticket_id": f"test-ticket-{i}",
                "template_id": "microservice-python-v1",
                "parameters": {}
            }
            client.post("/api/v1/generate", json=payload)

        response = client.get("/api/v1/generate")

        assert response.status_code == 200
        data = response.json()
        assert data["total"] == 2
        assert len(data["requests"]) == 2
        assert "status_counts" in data


class TestProcessGenerationTask:
    """Testes para _process_generation_task"""

    @pytest.mark.asyncio
    async def test_process_generation_task_heuristic(self):
        """Testa processamento usando geração heurística."""
        # Limpar requisições
        request_id = "test-request-001"
        GENERATION_REQUESTS[request_id] = {
            "request_id": request_id,
            "status": "queued",
            "ticket_id": "test-ticket",
            "template_id": "microservice-python-v1",
            "parameters": {
                "service_name": "my-service",
                "language": "python"
            },
            "artifacts": [],
            "error": None,
            "created_at": datetime.utcnow().isoformat(),
            "updated_at": datetime.utcnow().isoformat()
        }

        # Executar task
        from src.api.generation_api import _process_generation_task
        await _process_generation_task(
            request_id=request_id,
            ticket_id="test-ticket",
            template_id="microservice-python-v1",
            parameters={"service_name": "my-service", "language": "python"}
        )

        # Verificar resultado
        assert GENERATION_REQUESTS[request_id]["status"] == "completed"
        assert len(GENERATION_REQUESTS[request_id]["artifacts"]) > 0
        assert "code_content" in GENERATION_REQUESTS[request_id]
        assert "my-service" in GENERATION_REQUESTS[request_id]["code_content"]

    @pytest.mark.asyncio
    async def test_process_generation_task_error(self):
        """Testa tratamento de erro na geração."""
        request_id = "test-request-error"
        GENERATION_REQUESTS[request_id] = {
            "request_id": request_id,
            "status": "queued",
            "ticket_id": "test-ticket",
            "template_id": "invalid",
            "parameters": {},  # Parâmetros vazios podem causar erro
            "artifacts": [],
            "error": None,
            "created_at": datetime.utcnow().isoformat(),
            "updated_at": datetime.utcnow().isoformat()
        }

        # Executar task (não deve falhar mesmo com erro)
        from src.api.generation_api import _process_generation_task
        await _process_generation_task(
            request_id=request_id,
            ticket_id="test-ticket",
            template_id="invalid",
            parameters={}
        )

        # Verificar que ou completou ou marcou erro
        assert GENERATION_REQUESTS[request_id]["status"] in ["completed", "failed"]


class TestGenerateCodeHeuristic:
    """Testes para _generate_code_heuristic"""

    def test_generate_python_code(self):
        """Testa geração de código Python."""
        code = _generate_code_heuristic(
            service_name="test-service",
            language="python",
            description="Test service",
            requirements=["fast"]
        )

        assert "test-service" in code
        assert "FastAPI" in code
        assert "/health" in code
        assert "Generated by Neural Code Forge" in code

    def test_generate_javascript_code(self):
        """Testa geração de código JavaScript."""
        code = _generate_code_heuristic(
            service_name="test-service",
            language="javascript",
            description="Test service",
            requirements=[]
        )

        assert "express" in code.lower()
        assert "/health" in code

    def test_generate_defaults_to_python(self):
        """Testa que linguagem desconhecida usa Python como fallback."""
        code = _generate_code_heuristic(
            service_name="test-service",
            language="unknown",
            description="Test",
            requirements=[]
        )

        # Deve gerar Python como fallback
        assert "FastAPI" in code or "python" in code.lower()

    def test_generated_code_has_proper_structure(self):
        """Testa que código gerado tem estrutura válida."""
        code = _generate_code_heuristic(
            service_name="my-api",
            language="python",
            description="API Description",
            requirements=["req1", "req2"]
        )

        # Verificar imports
        assert "import" in code

        # Verificar endpoints
        assert "@app.get" in code or "app.get" in code

        # Verificar que contém os parâmetros
        assert "my-api" in code


class TestGenerationApiIntegration:
    """Testes de integração do fluxo completo"""

    def test_full_generation_flow(self, client):
        """Testa fluxo completo: criar → aguardar → status."""
        # 1. Criar requisição
        payload = {
            "ticket_id": "integration-test-001",
            "template_id": "microservice-python-v1",
            "parameters": {
                "service_name": "integration-service",
                "language": "python",
                "description": "Integration test service"
            }
        }
        create_response = client.post("/api/v1/generate", json=payload)
        assert create_response.status_code == 202

        request_id = create_response.json()["request_id"]

        # 2. Aguardar processamento
        import time
        time.sleep(3)

        # 3. Verificar status completo
        status_response = client.get(f"/api/v1/generate/{request_id}")
        assert status_response.status_code == 200

        data = status_response.json()
        assert data["status"] == "completed"
        assert len(data["artifacts"]) > 0
        assert "integration-service" in data["code_preview"]

    def test_concurrent_generations(self, client):
        """Testa múltiplas gerações concorrentes."""
        import time

        # Criar 3 requisições concorrentes
        request_ids = []
        for i in range(3):
            payload = {
                "ticket_id": f"concurrent-test-{i}",
                "template_id": "microservice-python-v1",
                "parameters": {"service_name": f"service-{i}", "language": "python"}
            }
            response = client.post("/api/v1/generate", json=payload)
            assert response.status_code == 202
            request_ids.append(response.json()["request_id"])

        # Aguardar processamento
        time.sleep(5)

        # Verificar que todas completaram
        for request_id in request_ids:
            response = client.get(f"/api/v1/generate/{request_id}")
            assert response.status_code == 200
            data = response.json()
            assert data["status"] in ["completed", "failed"]  # Pode falhar, não deve crashar
