apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Chart.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - port: http
          protocol: TCP
      {{- if eq .Values.service.type "LoadBalancer" }}
      from: []  # Permitir tráfico de qualquer origem (gateway público)
      {{- else }}
      from:
        - podSelector: {}  # Permitir tráfico de pods no mesmo namespace
      {{- end }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: kafka
      ports:
        - port: 9092
    - to:
        - podSelector:
            matchLabels:
              app: mongodb
      ports:
        - port: 27017
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - port: 6379
    - to: []  # Permitir todo egress para DNS e external APIs
