# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlu_pb2 as nlu__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in nlu_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NLUServiceStub(object):
    """Serviço NLU centralizado para processamento de linguagem natural
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Parse = channel.unary_unary(
                '/neural_hive.nlu.NLUService/Parse',
                request_serializer=nlu__pb2.ParseRequest.SerializeToString,
                response_deserializer=nlu__pb2.ParseResponse.FromString,
                _registered_method=True)
        self.ClassifyDomain = channel.unary_unary(
                '/neural_hive.nlu.NLUService/ClassifyDomain',
                request_serializer=nlu__pb2.ClassifyDomainRequest.SerializeToString,
                response_deserializer=nlu__pb2.ClassifyDomainResponse.FromString,
                _registered_method=True)
        self.ExtractEntities = channel.unary_unary(
                '/neural_hive.nlu.NLUService/ExtractEntities',
                request_serializer=nlu__pb2.ExtractEntitiesRequest.SerializeToString,
                response_deserializer=nlu__pb2.ExtractEntitiesResponse.FromString,
                _registered_method=True)
        self.CalculateConfidence = channel.unary_unary(
                '/neural_hive.nlu.NLUService/CalculateConfidence',
                request_serializer=nlu__pb2.CalculateConfidenceRequest.SerializeToString,
                response_deserializer=nlu__pb2.CalculateConfidenceResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/neural_hive.nlu.NLUService/HealthCheck',
                request_serializer=nlu__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=nlu__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.DetectLanguage = channel.unary_unary(
                '/neural_hive.nlu.NLUService/DetectLanguage',
                request_serializer=nlu__pb2.DetectLanguageRequest.SerializeToString,
                response_deserializer=nlu__pb2.DetectLanguageResponse.FromString,
                _registered_method=True)


class NLUServiceServicer(object):
    """Serviço NLU centralizado para processamento de linguagem natural
    """

    def Parse(self, request, context):
        """Processa texto completo e retorna resultado NLU completo
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyDomain(self, request, context):
        """Classifica domínio do texto (BUSINESS/TECHNICAL/INFRASTRUCTURE/SECURITY)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExtractEntities(self, request, context):
        """Extrai entidades nomeadas do texto (NER)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateConfidence(self, request, context):
        """Calcula confiança do resultado NLU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check do serviço NLU
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectLanguage(self, request, context):
        """Detecta idioma do texto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLUServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=nlu__pb2.ParseRequest.FromString,
                    response_serializer=nlu__pb2.ParseResponse.SerializeToString,
            ),
            'ClassifyDomain': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyDomain,
                    request_deserializer=nlu__pb2.ClassifyDomainRequest.FromString,
                    response_serializer=nlu__pb2.ClassifyDomainResponse.SerializeToString,
            ),
            'ExtractEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.ExtractEntities,
                    request_deserializer=nlu__pb2.ExtractEntitiesRequest.FromString,
                    response_serializer=nlu__pb2.ExtractEntitiesResponse.SerializeToString,
            ),
            'CalculateConfidence': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateConfidence,
                    request_deserializer=nlu__pb2.CalculateConfidenceRequest.FromString,
                    response_serializer=nlu__pb2.CalculateConfidenceResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=nlu__pb2.HealthCheckRequest.FromString,
                    response_serializer=nlu__pb2.HealthCheckResponse.SerializeToString,
            ),
            'DetectLanguage': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectLanguage,
                    request_deserializer=nlu__pb2.DetectLanguageRequest.FromString,
                    response_serializer=nlu__pb2.DetectLanguageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neural_hive.nlu.NLUService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neural_hive.nlu.NLUService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NLUService(object):
    """Serviço NLU centralizado para processamento de linguagem natural
    """

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/Parse',
            nlu__pb2.ParseRequest.SerializeToString,
            nlu__pb2.ParseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyDomain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/ClassifyDomain',
            nlu__pb2.ClassifyDomainRequest.SerializeToString,
            nlu__pb2.ClassifyDomainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExtractEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/ExtractEntities',
            nlu__pb2.ExtractEntitiesRequest.SerializeToString,
            nlu__pb2.ExtractEntitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateConfidence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/CalculateConfidence',
            nlu__pb2.CalculateConfidenceRequest.SerializeToString,
            nlu__pb2.CalculateConfidenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/HealthCheck',
            nlu__pb2.HealthCheckRequest.SerializeToString,
            nlu__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectLanguage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.nlu.NLUService/DetectLanguage',
            nlu__pb2.DetectLanguageRequest.SerializeToString,
            nlu__pb2.DetectLanguageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
