# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pii_pb2 as pii__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pii_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PIIServiceStub(object):
    """Serviço PII centralizado para detecção e mascaramento de informações sensíveis
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/neural_hive.pii.PIIService/Detect',
                request_serializer=pii__pb2.DetectRequest.SerializeToString,
                response_deserializer=pii__pb2.DetectResponse.FromString,
                _registered_method=True)
        self.Mask = channel.unary_unary(
                '/neural_hive.pii.PIIService/Mask',
                request_serializer=pii__pb2.MaskRequest.SerializeToString,
                response_deserializer=pii__pb2.MaskResponse.FromString,
                _registered_method=True)
        self.Unmask = channel.unary_unary(
                '/neural_hive.pii.PIIService/Unmask',
                request_serializer=pii__pb2.UnmaskRequest.SerializeToString,
                response_deserializer=pii__pb2.UnmaskResponse.FromString,
                _registered_method=True)
        self.DetectAndMask = channel.unary_unary(
                '/neural_hive.pii.PIIService/DetectAndMask',
                request_serializer=pii__pb2.DetectAndMaskRequest.SerializeToString,
                response_deserializer=pii__pb2.DetectAndMaskResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/neural_hive.pii.PIIService/HealthCheck',
                request_serializer=pii__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=pii__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/neural_hive.pii.PIIService/GetCapabilities',
                request_serializer=pii__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=pii__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.ValidateMaskToken = channel.unary_unary(
                '/neural_hive.pii.PIIService/ValidateMaskToken',
                request_serializer=pii__pb2.ValidateMaskTokenRequest.SerializeToString,
                response_deserializer=pii__pb2.ValidateMaskTokenResponse.FromString,
                _registered_method=True)


class PIIServiceServicer(object):
    """Serviço PII centralizado para detecção e mascaramento de informações sensíveis
    """

    def Detect(self, request, context):
        """Detecta PII em texto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Mask(self, request, context):
        """Mascara PII em texto
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unmask(self, request, context):
        """Remove máscara (quando reversível, AES-256-GCM)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectAndMask(self, request, context):
        """Detecta e mascara em uma única operação
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check do serviço PII
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Obtém capacidades do serviço
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateMaskToken(self, request, context):
        """Valida token de mascaramento (para unmask reversível)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PIIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=pii__pb2.DetectRequest.FromString,
                    response_serializer=pii__pb2.DetectResponse.SerializeToString,
            ),
            'Mask': grpc.unary_unary_rpc_method_handler(
                    servicer.Mask,
                    request_deserializer=pii__pb2.MaskRequest.FromString,
                    response_serializer=pii__pb2.MaskResponse.SerializeToString,
            ),
            'Unmask': grpc.unary_unary_rpc_method_handler(
                    servicer.Unmask,
                    request_deserializer=pii__pb2.UnmaskRequest.FromString,
                    response_serializer=pii__pb2.UnmaskResponse.SerializeToString,
            ),
            'DetectAndMask': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectAndMask,
                    request_deserializer=pii__pb2.DetectAndMaskRequest.FromString,
                    response_serializer=pii__pb2.DetectAndMaskResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=pii__pb2.HealthCheckRequest.FromString,
                    response_serializer=pii__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=pii__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=pii__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'ValidateMaskToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateMaskToken,
                    request_deserializer=pii__pb2.ValidateMaskTokenRequest.FromString,
                    response_serializer=pii__pb2.ValidateMaskTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neural_hive.pii.PIIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('neural_hive.pii.PIIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PIIService(object):
    """Serviço PII centralizado para detecção e mascaramento de informações sensíveis
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/Detect',
            pii__pb2.DetectRequest.SerializeToString,
            pii__pb2.DetectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Mask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/Mask',
            pii__pb2.MaskRequest.SerializeToString,
            pii__pb2.MaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unmask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/Unmask',
            pii__pb2.UnmaskRequest.SerializeToString,
            pii__pb2.UnmaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectAndMask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/DetectAndMask',
            pii__pb2.DetectAndMaskRequest.SerializeToString,
            pii__pb2.DetectAndMaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/HealthCheck',
            pii__pb2.HealthCheckRequest.SerializeToString,
            pii__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/GetCapabilities',
            pii__pb2.GetCapabilitiesRequest.SerializeToString,
            pii__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateMaskToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/neural_hive.pii.PIIService/ValidateMaskToken',
            pii__pb2.ValidateMaskTokenRequest.SerializeToString,
            pii__pb2.ValidateMaskTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
