apiVersion: v1
kind: Service
metadata:
  name: scout-mcp-server
  labels:
    {{- include "scout-mcp-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mcp
      protocol: TCP
      name: mcp
  selector:
    {{- include "scout-mcp-server.selectorLabels" . | nindent 4 }}
