apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster-config
  namespace: redis-cluster
data:
  redis_host: "redis-cluster.redis-cluster.svc.cluster.local"
  redis_port: "6379"
  redis_tls_enabled: "true"
  redis_cluster_mode: "true"
  redis_sentinel_enabled: "false"