# Namespace para Ambiente de Staging
apiVersion: v1
kind: Namespace
metadata:
  name: neural-hive-staging
  labels:
    environment: staging
    project: neural-hive-mind
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
