#!/usr/bin/env python3
"""
Fix imports in generated protobuf gRPC files.

This script converts absolute imports to relative imports in *_pb2_grpc.py files
generated by protoc. The generated files use imports like:
    import orchestrator_strategic_pb2 as orchestrator__strategic__pb2

Which should be:
    from . import orchestrator_strategic_pb2 as orchestrator__strategic__pb2

Usage:
    python scripts/fix_proto_imports.py
"""
import re
from pathlib import Path
import sys


def fix_proto_imports(proto_dir: Path) -> int:
    """
    Convert absolute imports to relative imports in *_pb2_grpc.py files.

    Args:
        proto_dir: Directory containing generated proto files

    Returns:
        Number of files fixed
    """
    fixed_count = 0

    for grpc_file in proto_dir.glob('*_pb2_grpc.py'):
        content = grpc_file.read_text()

        # Pattern: import foo_pb2 as bar
        # Replace: from . import foo_pb2 as bar
        # We only want to match the top-level import, not nested imports
        fixed = re.sub(
            r'^import (\w+_pb2) as',
            r'from . import \1 as',
            content,
            flags=re.MULTILINE
        )

        if fixed != content:
            grpc_file.write_text(fixed)
            fixed_count += 1
            print(f"Fixed imports in {grpc_file}")
        else:
            print(f"No changes needed for {grpc_file}")

    return fixed_count


if __name__ == '__main__':
    # Proto directories to fix
    proto_dirs = [
        Path('services/orchestrator-dynamic/src/proto'),
        Path('services/queen-agent/src/proto'),
        Path('services/self-healing-engine/src/proto'),
    ]

    total_fixed = 0
    for proto_dir in proto_dirs:
        if proto_dir.exists():
            print(f"\nProcessing {proto_dir}...")
            total_fixed += fix_proto_imports(proto_dir)
        else:
            print(f"Skipping {proto_dir} (does not exist)")

    print(f"\nTotal files fixed: {total_fixed}")

    # Exit with 0 if files were fixed, 1 if no changes were needed
    sys.exit(0 if total_fixed > 0 else 1)
