# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_registry_pb2 as service__registry__pb2


class ServiceRegistryStub(object):
    """Serviço de registro
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/Register',
                request_serializer=service__registry__pb2.RegisterRequest.SerializeToString,
                response_deserializer=service__registry__pb2.RegisterResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/Heartbeat',
                request_serializer=service__registry__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=service__registry__pb2.HeartbeatResponse.FromString,
                )
        self.Deregister = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/Deregister',
                request_serializer=service__registry__pb2.DeregisterRequest.SerializeToString,
                response_deserializer=service__registry__pb2.DeregisterResponse.FromString,
                )
        self.DiscoverAgents = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/DiscoverAgents',
                request_serializer=service__registry__pb2.DiscoverRequest.SerializeToString,
                response_deserializer=service__registry__pb2.DiscoverResponse.FromString,
                )
        self.GetAgent = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/GetAgent',
                request_serializer=service__registry__pb2.GetAgentRequest.SerializeToString,
                response_deserializer=service__registry__pb2.GetAgentResponse.FromString,
                )
        self.ListAgents = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/ListAgents',
                request_serializer=service__registry__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=service__registry__pb2.ListAgentsResponse.FromString,
                )
        self.WatchAgents = channel.unary_stream(
                '/neural_hive.service_registry.ServiceRegistry/WatchAgents',
                request_serializer=service__registry__pb2.WatchAgentsRequest.SerializeToString,
                response_deserializer=service__registry__pb2.AgentChangeEvent.FromString,
                )
        self.NotifyAgent = channel.unary_unary(
                '/neural_hive.service_registry.ServiceRegistry/NotifyAgent',
                request_serializer=service__registry__pb2.NotifyAgentRequest.SerializeToString,
                response_deserializer=service__registry__pb2.NotifyAgentResponse.FromString,
                )


class ServiceRegistryServicer(object):
    """Serviço de registro
    """

    def Register(self, request, context):
        """Registrar um novo agente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Enviar heartbeat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deregister(self, request, context):
        """Deregistrar agente
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverAgents(self, request, context):
        """Descobrir agentes baseado em capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgent(self, request, context):
        """Obter informações de um agente específico
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Listar todos os agentes
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchAgents(self, request, context):
        """Observar mudanças em agentes (server streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NotifyAgent(self, request, context):
        """Notificar agente via streaming/evento
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=service__registry__pb2.RegisterRequest.FromString,
                    response_serializer=service__registry__pb2.RegisterResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=service__registry__pb2.HeartbeatRequest.FromString,
                    response_serializer=service__registry__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Deregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Deregister,
                    request_deserializer=service__registry__pb2.DeregisterRequest.FromString,
                    response_serializer=service__registry__pb2.DeregisterResponse.SerializeToString,
            ),
            'DiscoverAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverAgents,
                    request_deserializer=service__registry__pb2.DiscoverRequest.FromString,
                    response_serializer=service__registry__pb2.DiscoverResponse.SerializeToString,
            ),
            'GetAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgent,
                    request_deserializer=service__registry__pb2.GetAgentRequest.FromString,
                    response_serializer=service__registry__pb2.GetAgentResponse.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=service__registry__pb2.ListAgentsRequest.FromString,
                    response_serializer=service__registry__pb2.ListAgentsResponse.SerializeToString,
            ),
            'WatchAgents': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchAgents,
                    request_deserializer=service__registry__pb2.WatchAgentsRequest.FromString,
                    response_serializer=service__registry__pb2.AgentChangeEvent.SerializeToString,
            ),
            'NotifyAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.NotifyAgent,
                    request_deserializer=service__registry__pb2.NotifyAgentRequest.FromString,
                    response_serializer=service__registry__pb2.NotifyAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'neural_hive.service_registry.ServiceRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceRegistry(object):
    """Serviço de registro
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/Register',
            service__registry__pb2.RegisterRequest.SerializeToString,
            service__registry__pb2.RegisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/Heartbeat',
            service__registry__pb2.HeartbeatRequest.SerializeToString,
            service__registry__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Deregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/Deregister',
            service__registry__pb2.DeregisterRequest.SerializeToString,
            service__registry__pb2.DeregisterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DiscoverAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/DiscoverAgents',
            service__registry__pb2.DiscoverRequest.SerializeToString,
            service__registry__pb2.DiscoverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/GetAgent',
            service__registry__pb2.GetAgentRequest.SerializeToString,
            service__registry__pb2.GetAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/ListAgents',
            service__registry__pb2.ListAgentsRequest.SerializeToString,
            service__registry__pb2.ListAgentsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/neural_hive.service_registry.ServiceRegistry/WatchAgents',
            service__registry__pb2.WatchAgentsRequest.SerializeToString,
            service__registry__pb2.AgentChangeEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NotifyAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/neural_hive.service_registry.ServiceRegistry/NotifyAgent',
            service__registry__pb2.NotifyAgentRequest.SerializeToString,
            service__registry__pb2.NotifyAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
