# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ticket_service_pb2 as ticket__service__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ticket_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TicketServiceStub(object):
    """Serviço de Execution Tickets
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTicket = channel.unary_unary(
                '/ticket_service.TicketService/GetTicket',
                request_serializer=ticket__service__pb2.GetTicketRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.GetTicketResponse.FromString,
                _registered_method=True)
        self.ListTickets = channel.unary_unary(
                '/ticket_service.TicketService/ListTickets',
                request_serializer=ticket__service__pb2.ListTicketsRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.ListTicketsResponse.FromString,
                _registered_method=True)
        self.UpdateTicketStatus = channel.unary_unary(
                '/ticket_service.TicketService/UpdateTicketStatus',
                request_serializer=ticket__service__pb2.UpdateTicketStatusRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.UpdateTicketStatusResponse.FromString,
                _registered_method=True)
        self.GenerateToken = channel.unary_unary(
                '/ticket_service.TicketService/GenerateToken',
                request_serializer=ticket__service__pb2.GenerateTokenRequest.SerializeToString,
                response_deserializer=ticket__service__pb2.GenerateTokenResponse.FromString,
                _registered_method=True)


class TicketServiceServicer(object):
    """Serviço de Execution Tickets
    """

    def GetTicket(self, request, context):
        """Buscar ticket por ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTickets(self, request, context):
        """Listar tickets com filtros
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTicketStatus(self, request, context):
        """Atualizar status do ticket
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateToken(self, request, context):
        """Gerar token JWT para ticket
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicket,
                    request_deserializer=ticket__service__pb2.GetTicketRequest.FromString,
                    response_serializer=ticket__service__pb2.GetTicketResponse.SerializeToString,
            ),
            'ListTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTickets,
                    request_deserializer=ticket__service__pb2.ListTicketsRequest.FromString,
                    response_serializer=ticket__service__pb2.ListTicketsResponse.SerializeToString,
            ),
            'UpdateTicketStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTicketStatus,
                    request_deserializer=ticket__service__pb2.UpdateTicketStatusRequest.FromString,
                    response_serializer=ticket__service__pb2.UpdateTicketStatusResponse.SerializeToString,
            ),
            'GenerateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateToken,
                    request_deserializer=ticket__service__pb2.GenerateTokenRequest.FromString,
                    response_serializer=ticket__service__pb2.GenerateTokenResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ticket_service.TicketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ticket_service.TicketService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TicketService(object):
    """Serviço de Execution Tickets
    """

    @staticmethod
    def GetTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket_service.TicketService/GetTicket',
            ticket__service__pb2.GetTicketRequest.SerializeToString,
            ticket__service__pb2.GetTicketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket_service.TicketService/ListTickets',
            ticket__service__pb2.ListTicketsRequest.SerializeToString,
            ticket__service__pb2.ListTicketsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTicketStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket_service.TicketService/UpdateTicketStatus',
            ticket__service__pb2.UpdateTicketStatusRequest.SerializeToString,
            ticket__service__pb2.UpdateTicketStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ticket_service.TicketService/GenerateToken',
            ticket__service__pb2.GenerateTokenRequest.SerializeToString,
            ticket__service__pb2.GenerateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
