# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ticket_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'ticket_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14ticket_service.proto\x12\x0eticket_service\"%\n\x10GetTicketRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\"I\n\x11GetTicketResponse\x12\x34\n\x06ticket\x18\x01 \x01(\x0b\x32$.ticket_service.ExecutionTicketProto\"T\n\x12ListTicketsRequest\x12\x0f\n\x07plan_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x05\x12\r\n\x05limit\x18\x04 \x01(\x05\"[\n\x13ListTicketsResponse\x12\x35\n\x07tickets\x18\x01 \x03(\x0b\x32$.ticket_service.ExecutionTicketProto\x12\r\n\x05total\x18\x02 \x01(\x05\"U\n\x19UpdateTicketStatusRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"R\n\x1aUpdateTicketStatusResponse\x12\x34\n\x06ticket\x18\x01 \x01(\x0b\x32$.ticket_service.ExecutionTicketProto\")\n\x14GenerateTokenRequest\x12\x11\n\tticket_id\x18\x01 \x01(\t\"A\n\x15GenerateTokenResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x12\n\nexpires_at\x18\x02 \x01(\x03\"\xbc\x01\n\x14\x45xecutionTicketProto\x12\x11\n\tticket_id\x18\x01 \x01(\t\x12\x0f\n\x07plan_id\x18\x02 \x01(\t\x12\x11\n\tintent_id\x18\x03 \x01(\t\x12\x0f\n\x07task_id\x18\x04 \x01(\t\x12\x11\n\ttask_type\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x0e\n\x06status\x18\x07 \x01(\t\x12\x10\n\x08priority\x18\x08 \x01(\t\x12\x12\n\ncreated_at\x18\t \x01(\x03\x32\x84\x03\n\rTicketService\x12P\n\tGetTicket\x12 .ticket_service.GetTicketRequest\x1a!.ticket_service.GetTicketResponse\x12V\n\x0bListTickets\x12\".ticket_service.ListTicketsRequest\x1a#.ticket_service.ListTicketsResponse\x12k\n\x12UpdateTicketStatus\x12).ticket_service.UpdateTicketStatusRequest\x1a*.ticket_service.UpdateTicketStatusResponse\x12\\\n\rGenerateToken\x12$.ticket_service.GenerateTokenRequest\x1a%.ticket_service.GenerateTokenResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ticket_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTICKETREQUEST']._serialized_start=40
  _globals['_GETTICKETREQUEST']._serialized_end=77
  _globals['_GETTICKETRESPONSE']._serialized_start=79
  _globals['_GETTICKETRESPONSE']._serialized_end=152
  _globals['_LISTTICKETSREQUEST']._serialized_start=154
  _globals['_LISTTICKETSREQUEST']._serialized_end=238
  _globals['_LISTTICKETSRESPONSE']._serialized_start=240
  _globals['_LISTTICKETSRESPONSE']._serialized_end=331
  _globals['_UPDATETICKETSTATUSREQUEST']._serialized_start=333
  _globals['_UPDATETICKETSTATUSREQUEST']._serialized_end=418
  _globals['_UPDATETICKETSTATUSRESPONSE']._serialized_start=420
  _globals['_UPDATETICKETSTATUSRESPONSE']._serialized_end=502
  _globals['_GENERATETOKENREQUEST']._serialized_start=504
  _globals['_GENERATETOKENREQUEST']._serialized_end=545
  _globals['_GENERATETOKENRESPONSE']._serialized_start=547
  _globals['_GENERATETOKENRESPONSE']._serialized_end=612
  _globals['_EXECUTIONTICKETPROTO']._serialized_start=615
  _globals['_EXECUTIONTICKETPROTO']._serialized_end=803
  _globals['_TICKETSERVICE']._serialized_start=806
  _globals['_TICKETSERVICE']._serialized_end=1194
# @@protoc_insertion_point(module_scope)
