# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import consensus_engine_extensions_pb2 as consensus__engine__extensions__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in consensus_engine_extensions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConsensusOptimizationStub(object):
    """Extensões propostas para consensus_engine.proto
    Estas extensões permitem ao Optimizer Agents ajustar pesos dinamicamente

    Serviço para otimização de pesos de especialistas
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentWeights = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/GetCurrentWeights',
                request_serializer=consensus__engine__extensions__pb2.GetCurrentWeightsRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.GetCurrentWeightsResponse.FromString,
                _registered_method=True)
        self.UpdateWeights = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/UpdateWeights',
                request_serializer=consensus__engine__extensions__pb2.UpdateWeightsRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.UpdateWeightsResponse.FromString,
                _registered_method=True)
        self.ValidateWeightAdjustment = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/ValidateWeightAdjustment',
                request_serializer=consensus__engine__extensions__pb2.ValidateWeightAdjustmentRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.ValidateWeightAdjustmentResponse.FromString,
                _registered_method=True)
        self.RollbackWeights = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/RollbackWeights',
                request_serializer=consensus__engine__extensions__pb2.RollbackWeightsRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.RollbackWeightsResponse.FromString,
                _registered_method=True)
        self.GetConsensusMetrics = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/GetConsensusMetrics',
                request_serializer=consensus__engine__extensions__pb2.GetConsensusMetricsRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.GetConsensusMetricsResponse.FromString,
                _registered_method=True)
        self.GetWeightHistory = channel.unary_unary(
                '/consensus_engine.ConsensusOptimization/GetWeightHistory',
                request_serializer=consensus__engine__extensions__pb2.GetWeightHistoryRequest.SerializeToString,
                response_deserializer=consensus__engine__extensions__pb2.GetWeightHistoryResponse.FromString,
                _registered_method=True)


class ConsensusOptimizationServicer(object):
    """Extensões propostas para consensus_engine.proto
    Estas extensões permitem ao Optimizer Agents ajustar pesos dinamicamente

    Serviço para otimização de pesos de especialistas
    """

    def GetCurrentWeights(self, request, context):
        """Obter pesos atuais dos especialistas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateWeights(self, request, context):
        """Atualizar pesos dos especialistas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateWeightAdjustment(self, request, context):
        """Validar ajuste de pesos antes de aplicar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackWeights(self, request, context):
        """Reverter pesos para versão anterior
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConsensusMetrics(self, request, context):
        """Obter métricas de consenso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWeightHistory(self, request, context):
        """Obter histórico de ajustes de peso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusOptimizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentWeights,
                    request_deserializer=consensus__engine__extensions__pb2.GetCurrentWeightsRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.GetCurrentWeightsResponse.SerializeToString,
            ),
            'UpdateWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateWeights,
                    request_deserializer=consensus__engine__extensions__pb2.UpdateWeightsRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.UpdateWeightsResponse.SerializeToString,
            ),
            'ValidateWeightAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateWeightAdjustment,
                    request_deserializer=consensus__engine__extensions__pb2.ValidateWeightAdjustmentRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.ValidateWeightAdjustmentResponse.SerializeToString,
            ),
            'RollbackWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackWeights,
                    request_deserializer=consensus__engine__extensions__pb2.RollbackWeightsRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.RollbackWeightsResponse.SerializeToString,
            ),
            'GetConsensusMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConsensusMetrics,
                    request_deserializer=consensus__engine__extensions__pb2.GetConsensusMetricsRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.GetConsensusMetricsResponse.SerializeToString,
            ),
            'GetWeightHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeightHistory,
                    request_deserializer=consensus__engine__extensions__pb2.GetWeightHistoryRequest.FromString,
                    response_serializer=consensus__engine__extensions__pb2.GetWeightHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consensus_engine.ConsensusOptimization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('consensus_engine.ConsensusOptimization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConsensusOptimization(object):
    """Extensões propostas para consensus_engine.proto
    Estas extensões permitem ao Optimizer Agents ajustar pesos dinamicamente

    Serviço para otimização de pesos de especialistas
    """

    @staticmethod
    def GetCurrentWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/GetCurrentWeights',
            consensus__engine__extensions__pb2.GetCurrentWeightsRequest.SerializeToString,
            consensus__engine__extensions__pb2.GetCurrentWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/UpdateWeights',
            consensus__engine__extensions__pb2.UpdateWeightsRequest.SerializeToString,
            consensus__engine__extensions__pb2.UpdateWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateWeightAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/ValidateWeightAdjustment',
            consensus__engine__extensions__pb2.ValidateWeightAdjustmentRequest.SerializeToString,
            consensus__engine__extensions__pb2.ValidateWeightAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/RollbackWeights',
            consensus__engine__extensions__pb2.RollbackWeightsRequest.SerializeToString,
            consensus__engine__extensions__pb2.RollbackWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConsensusMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/GetConsensusMetrics',
            consensus__engine__extensions__pb2.GetConsensusMetricsRequest.SerializeToString,
            consensus__engine__extensions__pb2.GetConsensusMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWeightHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/consensus_engine.ConsensusOptimization/GetWeightHistory',
            consensus__engine__extensions__pb2.GetWeightHistoryRequest.SerializeToString,
            consensus__engine__extensions__pb2.GetWeightHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
