# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import orchestrator_extensions_pb2 as orchestrator__extensions__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in orchestrator_extensions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OrchestratorOptimizationStub(object):
    """Extensões propostas para orchestrator.proto
    Estas extensões permitem ao Optimizer Agents ajustar SLOs dinamicamente

    Serviço para otimização de SLOs
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCurrentSLOs = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/GetCurrentSLOs',
                request_serializer=orchestrator__extensions__pb2.GetCurrentSLOsRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.GetCurrentSLOsResponse.FromString,
                _registered_method=True)
        self.UpdateSLOs = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/UpdateSLOs',
                request_serializer=orchestrator__extensions__pb2.UpdateSLOsRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.UpdateSLOsResponse.FromString,
                _registered_method=True)
        self.ValidateSLOAdjustment = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/ValidateSLOAdjustment',
                request_serializer=orchestrator__extensions__pb2.ValidateSLOAdjustmentRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.ValidateSLOAdjustmentResponse.FromString,
                _registered_method=True)
        self.RollbackSLOs = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/RollbackSLOs',
                request_serializer=orchestrator__extensions__pb2.RollbackSLOsRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.RollbackSLOsResponse.FromString,
                _registered_method=True)
        self.GetSLOComplianceMetrics = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/GetSLOComplianceMetrics',
                request_serializer=orchestrator__extensions__pb2.GetSLOComplianceMetricsRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.GetSLOComplianceMetricsResponse.FromString,
                _registered_method=True)
        self.GetErrorBudget = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/GetErrorBudget',
                request_serializer=orchestrator__extensions__pb2.GetErrorBudgetRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.GetErrorBudgetResponse.FromString,
                _registered_method=True)
        self.GetSLOHistory = channel.unary_unary(
                '/orchestrator.OrchestratorOptimization/GetSLOHistory',
                request_serializer=orchestrator__extensions__pb2.GetSLOHistoryRequest.SerializeToString,
                response_deserializer=orchestrator__extensions__pb2.GetSLOHistoryResponse.FromString,
                _registered_method=True)


class OrchestratorOptimizationServicer(object):
    """Extensões propostas para orchestrator.proto
    Estas extensões permitem ao Optimizer Agents ajustar SLOs dinamicamente

    Serviço para otimização de SLOs
    """

    def GetCurrentSLOs(self, request, context):
        """Obter SLOs atuais
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSLOs(self, request, context):
        """Atualizar SLOs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateSLOAdjustment(self, request, context):
        """Validar ajuste de SLO antes de aplicar
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackSLOs(self, request, context):
        """Reverter SLOs para versão anterior
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSLOComplianceMetrics(self, request, context):
        """Obter métricas de compliance de SLO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorBudget(self, request, context):
        """Obter error budget restante
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSLOHistory(self, request, context):
        """Obter histórico de ajustes de SLO
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OrchestratorOptimizationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCurrentSLOs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentSLOs,
                    request_deserializer=orchestrator__extensions__pb2.GetCurrentSLOsRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.GetCurrentSLOsResponse.SerializeToString,
            ),
            'UpdateSLOs': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSLOs,
                    request_deserializer=orchestrator__extensions__pb2.UpdateSLOsRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.UpdateSLOsResponse.SerializeToString,
            ),
            'ValidateSLOAdjustment': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateSLOAdjustment,
                    request_deserializer=orchestrator__extensions__pb2.ValidateSLOAdjustmentRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.ValidateSLOAdjustmentResponse.SerializeToString,
            ),
            'RollbackSLOs': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackSLOs,
                    request_deserializer=orchestrator__extensions__pb2.RollbackSLOsRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.RollbackSLOsResponse.SerializeToString,
            ),
            'GetSLOComplianceMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSLOComplianceMetrics,
                    request_deserializer=orchestrator__extensions__pb2.GetSLOComplianceMetricsRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.GetSLOComplianceMetricsResponse.SerializeToString,
            ),
            'GetErrorBudget': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorBudget,
                    request_deserializer=orchestrator__extensions__pb2.GetErrorBudgetRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.GetErrorBudgetResponse.SerializeToString,
            ),
            'GetSLOHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSLOHistory,
                    request_deserializer=orchestrator__extensions__pb2.GetSLOHistoryRequest.FromString,
                    response_serializer=orchestrator__extensions__pb2.GetSLOHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'orchestrator.OrchestratorOptimization', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('orchestrator.OrchestratorOptimization', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OrchestratorOptimization(object):
    """Extensões propostas para orchestrator.proto
    Estas extensões permitem ao Optimizer Agents ajustar SLOs dinamicamente

    Serviço para otimização de SLOs
    """

    @staticmethod
    def GetCurrentSLOs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/GetCurrentSLOs',
            orchestrator__extensions__pb2.GetCurrentSLOsRequest.SerializeToString,
            orchestrator__extensions__pb2.GetCurrentSLOsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSLOs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/UpdateSLOs',
            orchestrator__extensions__pb2.UpdateSLOsRequest.SerializeToString,
            orchestrator__extensions__pb2.UpdateSLOsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateSLOAdjustment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/ValidateSLOAdjustment',
            orchestrator__extensions__pb2.ValidateSLOAdjustmentRequest.SerializeToString,
            orchestrator__extensions__pb2.ValidateSLOAdjustmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackSLOs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/RollbackSLOs',
            orchestrator__extensions__pb2.RollbackSLOsRequest.SerializeToString,
            orchestrator__extensions__pb2.RollbackSLOsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSLOComplianceMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/GetSLOComplianceMetrics',
            orchestrator__extensions__pb2.GetSLOComplianceMetricsRequest.SerializeToString,
            orchestrator__extensions__pb2.GetSLOComplianceMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetErrorBudget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/GetErrorBudget',
            orchestrator__extensions__pb2.GetErrorBudgetRequest.SerializeToString,
            orchestrator__extensions__pb2.GetErrorBudgetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSLOHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/orchestrator.OrchestratorOptimization/GetSLOHistory',
            orchestrator__extensions__pb2.GetSLOHistoryRequest.SerializeToString,
            orchestrator__extensions__pb2.GetSLOHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
