apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    app: {{ .Chart.Name }}
type: Opaque
stringData:
  mongodb-uri: {{ .Values.secrets.mongodb_uri | default "" | quote }}
  redis-password: {{ .Values.secrets.redis_password | default "" | quote }}
  kafka-sasl-username: {{ .Values.secrets.kafka_sasl_username | default "" | quote }}
  kafka-sasl-password: {{ .Values.secrets.kafka_sasl_password | default "" | quote }}
  vault-token: {{ .Values.secrets.vault_token | default "" | quote }}
  spiffe-socket-path: {{ .Values.secrets.spiffe_socket_path | default "" | quote }}
