apiVersion: v2
name: software-engineering-pipeline
description: A Helm chart for Neural Hive Mind Software Engineering Pipeline service
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - pipeline
  - ci-cd
  - neural-hive-mind
  - software-engineering

maintainers:
  - name: Neural Hive Mind
    email: nhm@example.com

sources:
  - https://github.com/albinoJimy/Neural-Hive-Mind
