"""
SPIRE Workload API gRPC stubs
"""

import grpc
from . import workload_pb2


class SpiffeWorkloadAPIStub:
    """Client stub for SPIRE Workload API"""

    def __init__(self, channel: grpc.Channel):
        """
        Initialize the Workload API stub

        Args:
            channel: gRPC channel to SPIRE agent socket
        """
        self.channel = channel
        # In real implementation, these would be generated by protoc
        self.FetchJWTSVID = channel.unary_unary(
            '/SpiffeWorkloadAPI/FetchJWTSVID',
            request_serializer=workload_pb2.JWTSVIDRequest.SerializeToString,
            response_deserializer=workload_pb2.JWTSVIDResponse.FromString,
        )
        self.FetchJWTBundles = channel.unary_stream(
            '/SpiffeWorkloadAPI/FetchJWTBundles',
            request_serializer=lambda x: b'',
            response_deserializer=lambda x: x,
        )
        self.FetchX509SVID = channel.unary_stream(
            '/SpiffeWorkloadAPI/FetchX509SVID',
            request_serializer=workload_pb2.X509SVIDRequest.SerializeToString,
            response_deserializer=workload_pb2.X509SVIDResponse.FromString,
        )
        self.ValidateJWTSVID = channel.unary_unary(
            '/SpiffeWorkloadAPI/ValidateJWTSVID',
            request_serializer=workload_pb2.ValidateJWTSVIDRequest.SerializeToString,
            response_deserializer=workload_pb2.ValidateJWTSVIDResponse.FromString,
        )


class SpiffeWorkloadAPIServicer:
    """Server stub for SPIRE Workload API (not used in client code)"""
    pass
