import structlog
from typing import Optional, TYPE_CHECKING

from ..models.pipeline_context import PipelineContext
from ..clients.git_client import GitClient

if TYPE_CHECKING:
    from ..clients.mongodb_client import MongoDBClient

logger = structlog.get_logger()


class ApprovalGate:
    """Subpipeline 6: Gate de Aprovação"""

    def __init__(
        self,
        git_client: GitClient,
        mongodb_client: Optional['MongoDBClient'] = None,
        auto_approval_threshold: float = 0.9,
        min_quality_score: float = 0.5
    ):
        self.git_client = git_client
        self.mongodb_client = mongodb_client
        self.auto_approval_threshold = auto_approval_threshold
        self.min_quality_score = min_quality_score

    async def check_approval(self, context: PipelineContext):
        """
        Verifica se requer aprovação manual E commita código no repositório.

        Args:
            context: Contexto do pipeline
        """
        logger.info('approval_gate_started', pipeline_id=context.pipeline_id)

        # Calcular score de qualidade
        quality_score = context.calculate_quality_score()

        # Verificar issues críticos
        has_critical = context.has_critical_issues()

        # Determinar aprovação
        if quality_score >= self.auto_approval_threshold and not has_critical:
            logger.info('auto_approved', score=quality_score)
            context.metadata['approval'] = 'auto'
            # Commitar código mesmo quando auto-approved para manter histórico
            await self._commit_and_push(context, auto_approved=True)

        elif quality_score < self.min_quality_score or has_critical:
            logger.warning('auto_rejected', score=quality_score, critical=has_critical)
            context.metadata['approval'] = 'rejected'
            # Não commitar código rejeitado

        else:
            # Requer revisão manual - commitar e criar MR
            logger.info('requires_manual_review', score=quality_score)

            # Commitar e push código antes de criar MR
            await self._commit_and_push(context, auto_approved=False)

            # Criar Merge Request com branch já contendo código
            branch_name = f'code-forge-{context.pipeline_id[:8]}'
            repo_url = context.ticket.parameters.get('target_repo', '')

            if repo_url:
                mr_url = await self.git_client.create_merge_request(
                    repo_url=repo_url,
                    branch=branch_name,
                    title=f'Code Forge Pipeline {context.pipeline_id[:8]}',
                    description=f'''Quality Score: {quality_score:.2f}

Artifacts: {len(context.generated_artifacts)}
Generation Method: {context.generation_method or 'TEMPLATE'}
Template: {context.selected_template.template_id if context.selected_template else 'N/A'}

---
Auto-generated by Neural Code Forge
Pipeline ID: {context.pipeline_id}
Trace ID: {context.trace_id}'''
                )

                context.metadata['approval'] = 'manual'
                context.metadata['git_mr_url'] = mr_url
                context.metadata['git_branch'] = branch_name
                logger.info('merge_request_created', url=mr_url, branch=branch_name)
            else:
                logger.warning('no_target_repo_skip_mr', ticket_id=context.ticket.ticket_id)
                context.metadata['approval'] = 'manual_no_repo'

    async def _commit_and_push(self, context: PipelineContext, auto_approved: bool) -> Optional[str]:
        """
        Commita código gerado no repositório Git.

        Args:
            context: Contexto do pipeline com artefatos gerados
            auto_approved: Se foi auto-aprovado (afeta branch target)

        Returns:
            Nome da branch criada ou None se falhou
        """
        artifact = context.get_latest_artifact()
        if not artifact:
            logger.warning('no_artifact_to_commit', pipeline_id=context.pipeline_id)
            return None

        # Recuperar código do MongoDB
        if not self.mongodb_client:
            logger.warning('mongodb_client_not_available_skip_commit')
            return None

        try:
            code_content = await self.mongodb_client.get_artifact_content(artifact.artifact_id)
            if not code_content:
                logger.warning('artifact_content_empty', artifact_id=artifact.artifact_id)
                return None
        except Exception as e:
            logger.error('artifact_retrieval_failed', artifact_id=artifact.artifact_id, error=str(e))
            context.metadata['commit_error'] = f'Artifact retrieval failed: {str(e)}'
            return None

        # Determinar nome do arquivo baseado na linguagem
        language = artifact.language.lower() if artifact.language else 'python'
        filename = self._get_filename_for_language(language)

        # Criar branch
        branch_name = f'code-forge-{context.pipeline_id[:8]}'
        repo_url = context.ticket.parameters.get('target_repo', '')

        if not repo_url:
            logger.warning('no_target_repo_provided', ticket_id=context.ticket.ticket_id)
            return None

        try:
            # Criar branch
            await self.git_client.create_branch(repo_url, branch_name)

            # Preparar artefatos para commit
            artifacts = [
                {
                    'path': filename,
                    'content': code_content
                }
            ]

            # Adicionar README com metadados
            readme_content = self._generate_readme(context, artifact, code_content, auto_approved)
            artifacts.append({'path': 'README.md', 'content': readme_content})

            # Commitar artefatos
            commit_sha = await self.git_client.commit_artifacts(
                repo_url=repo_url,
                branch=branch_name,
                artifacts=artifacts,
                message=f'Code Forge: {artifact.artifact_type} generated via {artifact.generation_method if isinstance(artifact.generation_method, str) else artifact.generation_method.value}\n\nPipeline ID: {context.pipeline_id}\nArtifact ID: {artifact.artifact_id}'
            )

            # Push branch
            await self.git_client.push_branch(repo_url, branch_name)

            logger.info(
                'artifacts_committed_and_pushed',
                branch=branch_name,
                commit_sha=commit_sha[:8] if commit_sha else 'unknown',
                files_count=len(artifacts),
                auto_approved=auto_approved
            )

            context.metadata['git_commit_sha'] = commit_sha
            context.metadata['git_branch'] = branch_name

            return branch_name

        except Exception as e:
            logger.error('commit_push_failed', branch=branch_name, error=str(e))
            context.metadata['commit_error'] = str(e)
            return None

    def _get_filename_for_language(self, language: str) -> str:
        """
        Retorna o nome do arquivo principal baseado na linguagem.

        Args:
            language: Linguagem do artefato

        Returns:
            Nome do arquivo
        """
        filename_map = {
            'python': 'main.py',
            'javascript': 'index.js',
            'typescript': 'index.ts',
            'go': 'main.go',
            'java': 'Main.java',
            'rust': 'main.rs',
            'ruby': 'main.rb',
            'php': 'index.php',
        }
        return filename_map.get(language, f'main.{language}')

    def _generate_readme(self, context, artifact, code_content: str, auto_approved: bool) -> str:
        """
        Gera conteúdo README.md com metadados do artefato.

        Args:
            context: Contexto do pipeline
            artifact: Artefato gerado
            code_content: Conteúdo do código gerado
            auto_approved: Se foi auto-aprovado

        Returns:
            Conteúdo do README.md
        """
        service_name = context.ticket.parameters.get('service_name', 'generated-service')
        description = context.ticket.parameters.get('description', 'Generated by Neural Code Forge')

        readme = f'''# {service_name}

{description}

## Generated by Neural Code Forge

- **Pipeline ID**: {context.pipeline_id}
- **Artifact ID**: {artifact.artifact_id}
- **Generated at**: {artifact.created_at.isoformat() if artifact.created_at else 'N/A'}
- **Generation Method**: {artifact.generation_method if isinstance(artifact.generation_method, str) else artifact.generation_method.value}
- **Language**: {artifact.language or 'N/A'}
- **Template**: {context.selected_template.template_id if context.selected_template else 'N/A'}
- **Confidence Score**: {artifact.confidence_score:.2f}

## Metadata

- **Ticket ID**: {context.ticket.ticket_id}
- **Plan ID**: {context.ticket.plan_id or 'N/A'}
- **Intent ID**: {context.ticket.intent_id or 'N/A'}
- **Trace ID**: {context.trace_id}
- **Auto-Approved**: {auto_approved}

## Quality Score

Quality Score: {context.calculate_quality_score():.2f}

## Artifacts

This repository contains:
- `{self._get_filename_for_language(artifact.language.lower() if artifact.language else 'python')}` - Main source file

---

*This code was auto-generated. Review before using in production.*
'''
        return readme
