"""
Gerador avançado de IaC (Infrastructure as Code).

Suporta:
- Terraform modules completos com recursos AWS/GCP/Azure
- Helm charts com todos os templates Kubernetes
- Kubernetes manifests (Deployment, Service, ConfigMap, etc.)
- CloudFormation templates para AWS
"""

from typing import Any, Optional

import structlog

logger = structlog.get_logger()


class IaCGenerator:
    """
    Gerador de IaC com suporte a múltiplos providers e formatos.
    """

    def __init__(self):
        self.supported_providers = ["aws", "gcp", "azure", "kubernetes"]
        self.supported_formats = ["terraform", "helm", "kubernetes", "cloudformation"]

    def generate_terraform_module(
        self, params: dict[str, Any], provider: str = "aws", resources: Optional[list[str]] = None
    ) -> str:
        """
        Gera módulo Terraform completo com recursos específicos.

        Args:
            params: Parâmetros do ticket
            provider: Cloud provider (aws, gcp, azure)
            resources: Lista de recursos a incluir

        Returns:
            String com código Terraform completo
        """
        service_name = params.get("service_name", "my-service")
        environment = params.get("environment", "dev")

        if resources is None:
            resources = ["s3_bucket", "dynamodb_table", "lambda_function"]

        terraform_code = f"""# Terraform Module - {service_name}
# Generated by Neural Code Forge
# Provider: {provider.upper()}
# Environment: {environment}

terraform {{
  required_version = ">= 1.0"
  required_providers {{
    {self._get_terraform_provider_block(provider)}
  }}
}}

# Provider configuration
{self._get_provider_config(provider, environment)}

# Variables
{self._generate_terraform_variables(service_name, environment)}

# Locals
{self._generate_terraform_locals(service_name, environment)}

# Resources
{self._generate_terraform_resources(provider, resources, service_name, environment)}

# Outputs
{self._generate_terraform_outputs(resources)}
"""
        return terraform_code

    def _get_terraform_provider_block(self, provider: str) -> str:
        """Retorna bloco de providers Terraform."""
        providers = {
            "aws": """aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }""",
            "gcp": """google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }""",
            "azure": """azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }""",
            "kubernetes": """kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.0"
    }""",
        }
        return providers.get(provider, providers["aws"])

    def _get_provider_config(self, provider: str, environment: str) -> str:
        """Retorna configuração do provider."""
        configs = {
            "aws": """provider "aws" {
  region  = var.aws_region
  default_tags {
    tags = local.common_tags
  }
}""",
            "gcp": """provider "google" {
  project = var.gcp_project
  region  = var.gcp_region
  zone    = var.gcp_zone
}""",
            "azure": """provider "azurerm" {
  features {}
}""",
            "kubernetes": """provider "kubernetes" {
  config_path = var.kubeconfig_path
}""",
        }
        return configs.get(provider, configs["aws"])

    def _generate_terraform_variables(self, service_name: str, environment: str) -> str:
        """Gera blocos de variáveis Terraform."""
        return f"""variable "aws_region" {{
  description = "AWS region for resources"
  type        = string
  default     = "us-east-1"
}}

variable "gcp_project" {{
  description = "GCP project ID"
  type        = string
  default     = ""
}}

variable "gcp_region" {{
  description = "GCP region"
  type        = string
  default     = "us-central1"
}}

variable "gcp_zone" {{
  description = "GCP zone"
  type        = string
  default     = "us-central1-a"
}}

variable "environment" {{
  description = "Environment name"
  type        = string
  default     = "{environment}"
}}

variable "service_name" {{
  description = "Service name"
  type        = string
  default     = "{service_name}"
}}

variable "tags" {{
  description = "Additional tags"
  type        = map(string)
  default     = {{}}
}}

variable "enable_monitoring" {{
  description = "Enable CloudWatch monitoring"
  type        = bool
  default     = true
}}

variable "enable_alarm" {{
  description = "Enable CloudWatch alarms"
  type        = bool
  default     = true
}}

variable "retention_days" {{
  description = "Log retention in days"
  type        = number
  default     = 30
}}
"""

    def _generate_terraform_locals(self, service_name: str, environment: str) -> str:
        """Gera blocos de locals Terraform."""
        return """locals {
  service_name_sanitized = replace(var.service_name, "-", "")

  common_tags = merge(
    {
      Name        = "${var.service_name}-${var.environment}"
      ManagedBy   = "Neural-Code-Forge"
      Environment = var.environment
      Service     = var.service_name
    },
    var.tags
  )

  naming_prefix = "${var.service_name}-${var.environment}"
}
"""

    def _generate_terraform_resources(
        self, provider: str, resources: list[str], service_name: str, environment: str
    ) -> str:
        """Gera recursos Terraform baseados no provider e lista."""
        if provider == "aws":
            return self._generate_aws_resources(resources, service_name, environment)
        elif provider == "gcp":
            return self._generate_gcp_resources(resources, service_name, environment)
        elif provider == "azure":
            return self._generate_azure_resources(resources, service_name, environment)
        else:
            return self._generate_kubernetes_terraform_resources(
                resources, service_name, environment
            )

    def _generate_aws_resources(
        self, resources: list[str], service_name: str, environment: str
    ) -> str:
        """Gera recursos AWS."""

        code_blocks = []

        if "s3_bucket" in resources:
            code_blocks.append(
                """
# S3 Bucket for artifacts and logs
resource "aws_s3_bucket" "artifacts" {
  bucket = "${local.naming_prefix}-artifacts"

  tags = local.common_tags

  force_destroy = var.environment == "dev" ? true : false
}

resource "aws_s3_bucket_versioning" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_server_side_encryption" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id

  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm = "AES256"
    }
  }
}

resource "aws_s3_bucket_lifecycle_configuration" "artifacts" {
  bucket = aws_s3_bucket.artifacts.id

  rule {
    id     = "log-expiration"
    status = "enabled"

    expiration {
      days = var.retention_days
    }

    noncurrent_version_expiration {
      noncurrent_days = 30
    }
  }
}
"""
            )

        if "dynamodb_table" in resources:
            code_blocks.append(
                """
# DynamoDB Table for state locking
resource "aws_dynamodb_table" "state_lock" {
  name           = "${local.naming_prefix}-lock"
  billing_mode   = "PAY_PER_REQUEST"
  hash_key       = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }

  server_side_encryption {
    enabled = true
  }

  point_in_time_recovery {
    enabled = var.environment != "dev"
  }

  tags = local.common_tags

  lifecycle {
    ignore_changes = [ttl]
  }
}
"""
            )

        if "lambda_function" in resources:
            code_blocks.append(
                """
# Lambda Function
resource "aws_lambda_function" "main" {
  filename      = "${var.service_name}.zip"
  function_name = "${local.naming_prefix}-lambda"
  role          = aws_iam_role.lambda_role.arn
  handler       = "index.handler"

  source_code_hash = filebase64sha256("${var.service_name}.zip")

  runtime = "python3.11"
  timeout = 30
  memory_size = 256

  environment {
    variables = {
      ENVIRONMENT = var.environment
      LOG_LEVEL  = "INFO"
    }
  }

  tags = local.common_tags
}

# IAM Role for Lambda
resource "aws_iam_role" "lambda_role" {
  name = "${local.naming_prefix}-lambda-role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
  })

  tags = local.common_tags
}

# Lambda CloudWatch Log Group
resource "aws_cloudwatch_log_group" "lambda_logs" {
  name              = "/aws/lambda/${aws_lambda_function.main.function_name}"
  retention_in_days = var.retention_days

  tags = local.common_tags
}
"""
            )

        if "vpc" in resources:
            code_blocks.append(
                """
# VPC
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-vpc"
  })
}

# Public Subnets
resource "aws_subnet" "public" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${count.index}.0/24"
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-public-${count.index}"
    Type = "public"
  })
}

# Private Subnets
resource "aws_subnet" "private" {
  count             = 2
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${count.index + 10}.0/24"
  availability_zone = data.aws_availability_zones.available.names[count.index]

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-private-${count.index}"
    Type = "private"
  })
}

# Internet Gateway
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-igw"
  })
}

# NAT Gateway
resource "aws_eip" "nat" {
  count  = 2
  domain = "vpc"

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-nat-eip-${count.index}"
  })

  depends_on = [aws_internet_gateway.main]
}

resource "aws_nat_gateway" "main" {
  count         = 2
  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-nat-${count.index}"
  })

  depends_on = [aws_internet_gateway.main]
}

# Route Tables
resource "aws_route_table" "public" {
  vpc_id = aws_vpc.main.id

  route {
    cidr_block = "0.0.0.0/0"
    gateway_id = aws_internet_gateway.main.id
  }

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-public-rt"
  })
}

resource "aws_route_table" "private" {
  count  = 2
  vpc_id = aws_vpc.main.id

  route {
    cidr_block     = "0.0.0.0/0"
    nat_gateway_id = aws_nat_gateway.main[count.index].id
  }

  tags = merge(local.common_tags, {
    Name = "${local.naming_prefix}-private-rt-${count.index}"
  })
}

# Route Table Associations
resource "aws_route_table_association" "public" {
  count          = 2
  subnet_id      = aws_subnet.public[count.index].id
  route_table_id = aws_route_table.public.id
}

resource "aws_route_table_association" "private" {
  count          = 2
  subnet_id      = aws_subnet.private[count.index].id
  route_table_id = aws_route_table.private[count.index].id
}

# Data source for availability zones
data "aws_availability_zones" "available" {
  state = "available"
}
"""
            )

        if "ecr_repository" in resources:
            code_blocks.append(
                """
# ECR Repository
resource "aws_ecr_repository" "main" {
  name                 = "${local.naming_prefix}-repo"
  image_tag_mutability = "MUTABLE"

  image_scanning_configuration {
    scan_on_push = true
  }

  tags = local.common_tags
}

# ECR Lifecycle Policy
resource "aws_ecr_lifecycle_policy" "main" {
  repository = aws_ecr_repository.main.name

  policy = jsonencode({
    rules = [
      {
        rulePriority = 1
        description  = "Keep last 10 images"
        selection = {
          tagStatus     = "tagged"
          tagPrefixList = ["v"]
          countType     = "imageCountMoreThan"
          countNumber   = 10
        }
        action = {
          type = "expire"
        }
      }
    ]
  })
}
"""
            )

        if "ecs_cluster" in resources:
            code_blocks.append(
                """
# ECS Cluster
resource "aws_ecs_cluster" "main" {
  name = "${local.naming_prefix}-cluster"

  setting {
    name  = "containerInsights"
    value = "enabled"
  }

  tags = local.common_tags
}

# ECS Task Definition
resource "aws_ecs_task_definition" "main" {
  family                   = "${local.naming_prefix}"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE"]
  cpu                      = "512"
  memory                   = "1024"

  container_definitions = jsonencode([
    {
      name      = "${var.service_name}"
      image     = "${aws_ecr_repository.main.repository_url}:latest"
      cpu       = 256
      memory    = 512
      essential = true

      port_mappings = [
        {
          containerPort = 8080
          protocol      = "tcp"
        }
      ]

      log_configuration = {
        logDriver = "awslogs"
        options = {
          "awslogs-group"         = aws_cloudwatch_log_group.main.name
          "awslogs-region"        = var.aws_region
          "awslogs-stream-prefix" = "ecs"
        }
      }
    }
  ])

  tags = local.common_tags
}

# ECS Service
resource "aws_ecs_service" "main" {
  name            = "${local.naming_prefix}-service"
  cluster         = aws_ecs_cluster.main.id
  task_definition = aws_ecs_task_definition.main.arn
  desired_count   = 2
  launch_type     = "FARGATE"

  network_configuration {
    subnets          = aws_subnet.private[*].id
    security_groups  = [aws_security_group.main.id]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = aws_lb_target_group.main.arn
    container_name   = var.service_name
    container_port   = 8080
  }

  tags = local.common_tags
}

# Security Group
resource "aws_security_group" "main" {
  name        = "${local.naming_prefix}-sg"
  description = "Security group for ${var.service_name}"
  vpc_id      = aws_vpc.main.id

  ingress {
    description      = "HTTP from ALB"
    from_port        = 8080
    to_port          = 8080
    protocol         = "tcp"
    security_groups  = [aws_security_group.lb.id]
  }

  egress {
    description = "All outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = local.common_tags
}

# CloudWatch Log Group
resource "aws_cloudwatch_log_group" "main" {
  name              = "/ecs/${local.naming_prefix}"
  retention_in_days = var.retention_days

  tags = local.common_tags
}
"""
            )

        return "\n".join(code_blocks)

    def _generate_gcp_resources(
        self, resources: list[str], service_name: str, environment: str
    ) -> str:
        """Gera recursos GCP."""
        return f"""# GCP Resources for {service_name}
# Generated by Neural Code Forge

# Compute Instance
resource "google_compute_instance" "main" {{
  name         = "${{var.service_name}}-${{var.environment}}-vm"
  machine_type = "e2-medium"
  zone         = var.gcp_zone

  boot_disk {{
    initialize_params {{
      image = "debian-cloud/debian-11"
      size  = 20
    }}
  }}

  network_interface {{
    network = "default"
    access_config {{}}
  }}

  labels = local.common_tags
}}

# Cloud Storage Bucket
resource "google_storage_bucket" "artifacts" {{
  name          = "${{var.service_name}}-${{var.environment}}-artifacts"
  location      = var.gcp_region
  force_destroy = var.environment == "dev" ? true : false
  uniform_bucket_level_access = true

  lifecycle_rule {{
    condition {{
      age = var.retention_days
    }}
    action {{
      type = "Delete"
    }}
  }}
}}
"""

    def _generate_azure_resources(
        self, resources: list[str], service_name: str, environment: str
    ) -> str:
        """Gera recursos Azure."""
        return f"""# Azure Resources for {service_name}
# Generated by Neural Code Forge

# Resource Group
resource "azurerm_resource_group" "main" {{
  name     = "${{var.service_name}}-${{var.environment}}-rg"
  location = var.azure_location
  tags     = local.common_tags
}}

# Storage Account
resource "azurerm_storage_account" "main" {{
  name                     = "${{replace(var.service_name, "-", "")}}${{var.environment}}sa"
  resource_group_name      = azurerm_resource_group.main.name
  location                 = azurerm_resource_group.main.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = local.common_tags
}}

# Container Registry
resource "azurerm_container_registry" "main" {{
  name                = "${{replace(var.service_name, "-", "")}}acr"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "Standard"
  admin_enabled        = false

  tags = local.common_tags
}}
"""

    def _generate_kubernetes_terraform_resources(
        self, resources: list[str], service_name: str, environment: str
    ) -> str:
        """Gera recursos Kubernetes via Terraform."""
        return f"""# Kubernetes Resources for {service_name}
# Generated by Neural Code Forge

# Namespace
resource "kubernetes_namespace" "main" {{
  metadata {{
    name = "${{var.service_name}}-${{var.environment}}"
    labels = local.common_tags
  }}
}}

# Deployment
resource "kubernetes_deployment" "main" {{
  metadata {{
    name      = var.service_name
    namespace = kubernetes_namespace.main.metadata[0].name
    labels    = local.common_tags
  }}

  spec {{
    replicas = 3

    selector {{
      match_labels {{
        app = var.service_name
      }}
    }}

    template {{
      metadata {{
        labels = merge(local.common_tags, {{
          app = var.service_name
          version = "v1"
        }})
      }}

      spec {{
        container {{
          name  = var.service_name
          image = "${{var.service_name}}:latest"
          resources {{
            limits = {{
              cpu    = "500m"
              memory = "512Mi"
            }}
            requests {{
              cpu    = "250m"
              memory = "256Mi"
            }}
          }}

          port {{
            container_port = 8080
          }}

          liveness_probe {{
            http_get {{
              path = "/health"
              port = 8080
            }}
            initial_delay_seconds = 30
            period_seconds        = 10
          }}

          readiness_probe {{
            http_get {{
              path = "/health"
              port = 8080
            }}
            initial_delay_seconds = 5
            period_seconds        = 5
          }}
        }}
      }}
    }}
  }}
}}

# Service
resource "kubernetes_service" "main" {{
  metadata {{
    name      = var.service_name
    namespace = kubernetes_namespace.main.metadata[0].name
    labels    = local.common_tags
  }}

  spec {{
    selector {{
      app = var.service_name
    }}

    port {{
      protocol    = "TCP"
      port        = 80
      target_port = 8080
    }}

    type = "ClusterIP"
  }}
}}
"""

    def _generate_terraform_outputs(self, resources: list[str]) -> str:
        """Gera outputs Terraform."""
        outputs = []

        outputs.append(
            """
output "service_name" {
  description = "Service name"
  value       = var.service_name
}

output "environment" {
  description = "Environment"
  value       = var.environment
}

output "common_tags" {
  description = "Common tags applied to resources"
  value       = local.common_tags
}
"""
        )

        if "s3_bucket" in resources:
            outputs.append(
                """
output "s3_bucket_name" {
  description = "S3 bucket name for artifacts"
  value       = aws_s3_bucket.artifacts.id
}

output "s3_bucket_arn" {
  description = "S3 bucket ARN"
  value       = aws_s3_bucket.artifacts.arn
}
"""
            )

        if "dynamodb_table" in resources:
            outputs.append(
                """
output "dynamodb_table_name" {
  description = "DynamoDB table name"
  value       = aws_dynamodb_table.state_lock.name
}

output "dynamodb_table_arn" {
  description = "DynamoDB table ARN"
  value       = aws_dynamodb_table.state_lock.arn
}
"""
            )

        if "lambda_function" in resources:
            outputs.append(
                """
output "lambda_function_name" {
  description = "Lambda function name"
  value       = aws_lambda_function.main.function_name
}

output "lambda_function_arn" {
  description = "Lambda function ARN"
  value       = aws_lambda_function.main.arn
}

output "lambda_iam_role_arn" {
  description = "Lambda IAM role ARN"
  value       = aws_iam_role.lambda_role.arn
}
"""
            )

        if "vpc" in resources:
            outputs.append(
                """
output "vpc_id" {
  description = "VPC ID"
  value       = aws_vpc.main.id
}

output "public_subnet_ids" {
  description = "Public subnet IDs"
  value       = aws_subnet.public[*].id
}

output "private_subnet_ids" {
  description = "Private subnet IDs"
  value       = aws_subnet.private[*].id
}

output "internet_gateway_id" {
  description = "Internet Gateway ID"
  value       = aws_internet_gateway.main.id
}
"""
            )

        if "ecs_cluster" in resources:
            outputs.append(
                """
output "ecs_cluster_id" {
  description = "ECS cluster ID"
  value       = aws_ecs_cluster.main.id
}

output "ecs_cluster_arn" {
  description = "ECS cluster ARN"
  value       = aws_ecs_cluster.main.arn
}

output "ecs_service_name" {
  description = "ECS service name"
  value       = aws_ecs_service.main.name
}

output "ecr_repository_url" {
  description = "ECR repository URL"
  value       = aws_ecr_repository.main.repository_url
}
"""
            )

        return "\n".join(outputs)

    def generate_helm_chart(
        self, params: dict[str, Any], templates: Optional[list[str]] = None
    ) -> dict[str, str]:
        """
        Gera Helm Chart completo com todos os templates necessários.

        Args:
            params: Parâmetros do ticket
            templates: Lista de templates a incluir

        Returns:
            Dict com nome do arquivo e conteúdo
        """
        service_name = params.get("service_name", "my-service")
        description = params.get("description", "Generated by Neural Code Forge")

        if templates is None:
            templates = ["deployment", "service", "configmap", "hpa", "ingress", "serviceaccount"]

        chart_files = {}

        # Chart.yaml
        chart_files[
            "Chart.yaml"
        ] = f"""apiVersion: v2
name: {service_name}
description: {description}
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - microservice
  - neural-hive-mind
maintainers:
  - name: Neural Hive Mind
    email: team@neuralhive.com
home: https://github.com/neural-hive-mind/{service_name}
sources:
  - https://github.com/neural-hive-mind/{service_name}
icon: https://neuralhive.com/logo.png
"""

        # values.yaml
        chart_files["values.yaml"] = self._generate_helm_values(service_name)

        # templates/
        if "deployment" in templates:
            chart_files["templates/deployment.yaml"] = self._generate_helm_deployment(service_name)

        if "service" in templates:
            chart_files["templates/service.yaml"] = self._generate_helm_service(service_name)

        if "configmap" in templates:
            chart_files["templates/configmap.yaml"] = self._generate_helm_configmap(service_name)

        if "hpa" in templates:
            chart_files["templates/hpa.yaml"] = self._generate_helm_hpa(service_name)

        if "ingress" in templates:
            chart_files["templates/ingress.yaml"] = self._generate_helm_ingress(service_name)

        if "serviceaccount" in templates:
            chart_files["templates/serviceaccount.yaml"] = self._generate_helm_serviceaccount(
                service_name
            )

        # NOTES.txt
        chart_files[
            "templates/NOTES.txt"
        ] = f"""Thank you for installing {service_name}!

Your release is named {{{{ .Release.Name }}}}.
To learn more about the release, try:

  $ helm status {{{{ .Release.Name }}}}
  $ helm get all {{{{ .Release.Name }}}}

For more information on running and configuring {service_name}, see the documentation at:
  https://github.com/neural-hive-mind/{service_name}
"""

        # _helpers.tpl
        chart_files[
            "templates/_helpers.tpl"
        ] = """{{/*
Expand the name of the chart.
*/}}
{{- define "service.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "service.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "service.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "service.labels" -}}
helm.sh/chart: {{ include "service.chart" . }}
{{ include "service.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "service.selectorLabels" -}}
app.kubernetes.io/name: {{ include "service.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
"""

        return chart_files

    def _generate_helm_values(self, service_name: str) -> str:
        """Gera values.yaml completo."""
        return f"""# Default values for {service_name}
replicaCount: 2

image:
  repository: {service_name}
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {{}}
  name: ""

podAnnotations: {{}}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {{}}

ingress:
  enabled: false
  className: "nginx"
  annotations: {{}}
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: {service_name}.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {{}}

tolerations: []

affinity: {{}}

# Probes
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Environment variables
env:
  - name: LOG_LEVEL
    value: "INFO"
  - name: ENVIRONMENT
    value: "production"

# ConfigMap
configmap:
  enabled: true
  data:
    APP_NAME: {service_name}
    PORT: "8080"

# Secret
secret:
  enabled: false
  data: {{}}

# Service Monitor for Prometheus
serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
"""

    def _generate_helm_deployment(self, service_name: str) -> str:
        """Gera template de deployment."""
        return """apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "service.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          {{- if .Values.configmap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ include "service.fullname" . }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {{}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
"""

    def _generate_helm_service(self, service_name: str) -> str:
        """Gera template de service."""
        return """apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "service.selectorLabels" . | nindent 4 }}
"""

    def _generate_helm_configmap(self, service_name: str) -> str:
        """Gera template de configmap."""
        return """{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
"""

    def _generate_helm_hpa(self, service_name: str) -> str:
        """Gera template de HorizontalPodAutoscaler."""
        return """{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "service.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
"""

    def _generate_helm_ingress(self, service_name: str) -> str:
        """Gera template de ingress."""
        return """{{- if .Values.ingress.enabled -}}
{{- $fullName := include "service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- end }}
"""

    def _generate_helm_serviceaccount(self, service_name: str) -> str:
        """Gera template de service account."""
        return """{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
"""

    def generate_kubernetes_manifests(
        self, params: dict[str, Any], resources: Optional[list[str]] = None
    ) -> dict[str, str]:
        """
        Gera manifestos Kubernetes nativos (sem Helm).

        Args:
            params: Parâmetros do ticket
            resources: Lista de recursos a incluir

        Returns:
            Dict com nome do arquivo e conteúdo YAML
        """
        service_name = params.get("service_name", "my-service")
        namespace = params.get("namespace", "default")

        if resources is None:
            resources = ["namespace", "deployment", "service", "configmap"]

        manifests = {}

        if "namespace" in resources:
            manifests[
                "00-namespace.yaml"
            ] = f"""apiVersion: v1
kind: Namespace
metadata:
  name: {namespace}
  labels:
    name: {namespace}
    environment: production
"""

        if "deployment" in resources:
            manifests[
                "10-deployment.yaml"
            ] = f"""apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service_name}
  namespace: {namespace}
  labels:
    app: {service_name}
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {service_name}
  template:
    metadata:
      labels:
        app: {service_name}
        version: v1
    spec:
      serviceAccountName: {service_name}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: {service_name}
        image: {service_name}:1.0.0
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {{}}
"""

        if "service" in resources:
            manifests[
                "20-service.yaml"
            ] = f"""apiVersion: v1
kind: Service
metadata:
  name: {service_name}
  namespace: {namespace}
  labels:
    app: {service_name}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: {service_name}
"""

        if "configmap" in resources:
            manifests[
                "30-configmap.yaml"
            ] = f"""apiVersion: v1
kind: ConfigMap
metadata:
  name: {service_name}
  namespace: {namespace}
data:
  APP_NAME: "{service_name}"
  PORT: "8080"
  LOG_LEVEL: "INFO"
"""

        if "serviceaccount" in resources:
            manifests[
                "05-serviceaccount.yaml"
            ] = f"""apiVersion: v1
kind: ServiceAccount
metadata:
  name: {service_name}
  namespace: {namespace}
"""

        return manifests

    def generate_cloudformation_template(self, params: dict[str, Any]) -> str:
        """
        Gera template CloudFormation para AWS.

        Args:
            params: Parâmetros do ticket

        Returns:
            String com template CloudFormation em YAML
        """
        service_name = params.get("service_name", "my-service")
        environment = params.get("environment", "dev")

        return f"""---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for {service_name} - Generated by Neural Code Forge'

Parameters:
  Environment:
    Type: String
    Default: {environment}
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - production

  VpcBlock:
    Type: String
    Default: 10.0.0.0/16
    Description: VPC CIDR block

  PublicSubnet1Block:
    Type: String
    Default: 10.0.1.0/24
    Description: Public subnet 1 CIDR block

  PublicSubnet2Block:
    Type: String
    Default: 10.0.2.0/24
    Description: Public subnet 2 CIDR block

  PrivateSubnet1Block:
    Type: String
    Default: 10.0.11.0/24
    Description: Private subnet 1 CIDR block

  PrivateSubnet2Block:
    Type: String
    Default: 10.0.12.0/24
    Description: Private subnet 2 CIDR block

  InstanceType:
    Type: String
    Default: t3.micro
    Description: EC2 instance type

  DesiredCapacity:
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 10

  MaxSize:
    Type: Number
    Default: 4
    MinValue: 1
    MaxValue: 20

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-vpc'
        - Key: Environment
          Value: !Ref Environment

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-igw'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  # Public Subnets
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet1Block
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-public-1'

  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PublicSubnet2Block
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-public-2'

  # Private Subnets
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet1Block
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-private-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: !Ref PrivateSubnet2Block
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-private-2'

  # NAT Gateways
  NATGateway1:
    Type: AWS::EC2::NatGateway
    DependsOn: VPCGatewayAttachment
    Properties:
      AllocationId: !GetAtt NATEIP1.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-nat-1'

  NATGateway2:
    Type: AWS::EC2::NatGateway
    DependsOn: VPCGatewayAttachment
    Properties:
      AllocationId: !GetAtt NATEIP2.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-nat-2'

  NATEIP1:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc

  NATEIP2:
    Type: AWS::EC2::EIP
    DependsOn: VPCGatewayAttachment
    Properties:
      Domain: vpc

  # Route Tables
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-public-rt'

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable

  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-private-rt-1'

  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet1
      RouteTableId: !Ref PrivateRouteTable1

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-private-rt-2'

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet2
      RouteTableId: !Ref PrivateRouteTable2

  # ECS Cluster
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${{service_name}}-${{Environment}}-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled

  # ECS Task Execution Role
  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  # ECS Task Definition
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${{service_name}}-${{Environment}}-task'
      Cpu: 512
      Memory: 1024
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ECSTaskExecutionRole
      ContainerDefinitions:
        - Name: {service_name}
          Image: !Sub '${{service_name}}:latest'
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: ecs
          Environment:
            - Name: ENVIRONMENT
              Value: !Ref Environment

  # ECS Service
  ECSService:
    Type: AWS::ECS::Service
    DependsOn: ECSServiceListener
    Properties:
      ServiceName: !Sub '${{service_name}}-${{Environment}}-service'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: !Ref DesiredCapacity
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
          SecurityGroups:
            - !Ref ContainerSecurityGroup
          AssignPublicIp: DISABLED

  # Application Load Balancer
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub '${{service_name}}-${{Environment}}-alb'
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref LoadBalancerSecurityGroup
      Type: application

  # Load Balancer Security Group
  LoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for load balancer
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-alb-sg'

  # Container Security Group
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for containers
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref LoadBalancerSecurityGroup
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub '${{service_name}}-${{Environment}}-container-sg'

  # Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      TargetGroupName: !Sub '${{service_name}}-${{Environment}}-tg'
      TargetType: ip
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VPC
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 3
      UnhealthyThresholdCount: 3

  # Listener
  ECSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  # Listener Rule
  ECSServiceListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  # CloudWatch Log Group
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${{service_name}}-${{Environment}}'
      RetentionInDays: 30

  # Auto Scaling
  ScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: !Ref MaxSize
      MinCapacity: !Ref DesiredCapacity
      ResourceId: !Sub service/${{ECSService.Name}}
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  ScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${{service_name}}-${{Environment}}-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        ScaleInCooldown: 300
        ScaleOutCooldown: 60
        TargetValue: 70.0

Outputs:
  ClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster

  ServiceName:
    Description: ECS Service Name
    Value: !Ref ECSService

  LoadBalancerDNS:
    Description: Load Balancer DNS Name
    Value: !GetAtt LoadBalancer.DNSName

  LoadBalancerURL:
    Description: Load Balancer URL
    Value: !Sub 'http://${{LoadBalancer.DNSName}}'

  VPCId:
    Description: VPC ID
    Value: !Ref VPC

  PublicSubnetIds:
    Description: Public Subnet IDs
    Value: !Join [',', [!Ref PublicSubnet1, !Ref PublicSubnet2]]

  PrivateSubnetIds:
    Description: Private Subnet IDs
    Value: !Join [',', [!Ref PrivateSubnet1, !Ref PrivateSubnet2]]
"""
