# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analyst_agent_pb2 as analyst__agent__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analyst_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalystAgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetInsight = channel.unary_unary(
                '/analyst_agent.AnalystAgentService/GetInsight',
                request_serializer=analyst__agent__pb2.GetInsightRequest.SerializeToString,
                response_deserializer=analyst__agent__pb2.GetInsightResponse.FromString,
                _registered_method=True)
        self.QueryInsights = channel.unary_unary(
                '/analyst_agent.AnalystAgentService/QueryInsights',
                request_serializer=analyst__agent__pb2.QueryInsightsRequest.SerializeToString,
                response_deserializer=analyst__agent__pb2.QueryInsightsResponse.FromString,
                _registered_method=True)
        self.ExecuteAnalysis = channel.unary_unary(
                '/analyst_agent.AnalystAgentService/ExecuteAnalysis',
                request_serializer=analyst__agent__pb2.ExecuteAnalysisRequest.SerializeToString,
                response_deserializer=analyst__agent__pb2.ExecuteAnalysisResponse.FromString,
                _registered_method=True)
        self.GetStatistics = channel.unary_unary(
                '/analyst_agent.AnalystAgentService/GetStatistics',
                request_serializer=analyst__agent__pb2.GetStatisticsRequest.SerializeToString,
                response_deserializer=analyst__agent__pb2.GetStatisticsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/analyst_agent.AnalystAgentService/HealthCheck',
                request_serializer=analyst__agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=analyst__agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class AnalystAgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetInsight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryInsights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalystAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInsight,
                    request_deserializer=analyst__agent__pb2.GetInsightRequest.FromString,
                    response_serializer=analyst__agent__pb2.GetInsightResponse.SerializeToString,
            ),
            'QueryInsights': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryInsights,
                    request_deserializer=analyst__agent__pb2.QueryInsightsRequest.FromString,
                    response_serializer=analyst__agent__pb2.QueryInsightsResponse.SerializeToString,
            ),
            'ExecuteAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteAnalysis,
                    request_deserializer=analyst__agent__pb2.ExecuteAnalysisRequest.FromString,
                    response_serializer=analyst__agent__pb2.ExecuteAnalysisResponse.SerializeToString,
            ),
            'GetStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatistics,
                    request_deserializer=analyst__agent__pb2.GetStatisticsRequest.FromString,
                    response_serializer=analyst__agent__pb2.GetStatisticsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=analyst__agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=analyst__agent__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analyst_agent.AnalystAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analyst_agent.AnalystAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalystAgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyst_agent.AnalystAgentService/GetInsight',
            analyst__agent__pb2.GetInsightRequest.SerializeToString,
            analyst__agent__pb2.GetInsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryInsights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyst_agent.AnalystAgentService/QueryInsights',
            analyst__agent__pb2.QueryInsightsRequest.SerializeToString,
            analyst__agent__pb2.QueryInsightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyst_agent.AnalystAgentService/ExecuteAnalysis',
            analyst__agent__pb2.ExecuteAnalysisRequest.SerializeToString,
            analyst__agent__pb2.ExecuteAnalysisResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyst_agent.AnalystAgentService/GetStatistics',
            analyst__agent__pb2.GetStatisticsRequest.SerializeToString,
            analyst__agent__pb2.GetStatisticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analyst_agent.AnalystAgentService/HealthCheck',
            analyst__agent__pb2.HealthCheckRequest.SerializeToString,
            analyst__agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
